#include "frodo_sample_n.h"
#include "sdat_avx2.h"
#include <stdio.h>
#include <string.h>
static const sdat_table*tabs_o[3]={&original_cdt_table_frodo640,&original_cdt_table_frodo976,&original_cdt_table_frodo1344};
static const sdat_table*tabs_s[3]={&sda_table_frodo640,&sda_table_frodo976,&sda_table_frodo1344};
static uint16_t ref_orig(uint16_t w,const sdat_table*t){const uint16_t*c=t->thresholds;uint16_t m=0,x=w>>1;for(size_t i=0;i<t->threshold_count;i++)m+=(uint16_t)(x>c[i]);return frodo_apply_sign(m,w&1);} 
static int test_orig(void){for(int ti=0;ti<3;ti++){uint16_t a[65536],b[65536];for(unsigned i=0;i<65536;i++)a[i]=b[i]=(uint16_t)i; if(frodo_original_sample_n(a,65536,tabs_o[ti]))return 10+ti; if(frodo_original_sample_n_avx2(b,65536,tabs_o[ti]))return 20+ti; for(unsigned i=0;i<65536;i++)if(a[i]!=ref_orig((uint16_t)i,tabs_o[ti])||b[i]!=a[i])return 30+ti; }return 0;}
static int test_sda_map(void){for(int ti=0;ti<3;ti++){const sdat_table*t=tabs_s[ti];for(uint32_t x=0;x<t->denominator_u64;x++)for(int sg=0;sg<2;sg++){uint16_t r=frodo_apply_sign(frodo_lookup_magnitude_scalar(x,t),(uint8_t)sg);uint16_t r2=r;if(r!=r2)return 1;}}return 0;}
static void putbits(uint8_t*b,size_t*bit,uint32_t v,unsigned bits){for(unsigned i=0;i<bits;i++){if((v>>i)&1)b[*bit/8]|=(uint8_t)(1u<<(*bit%8));(*bit)++;}}
static int test_reject(void){for(int ti=0;ti<3;ti++){const sdat_table*t=tabs_s[ti];uint8_t buf[32]={0};size_t bit=0;unsigned b=t->random_draw_bits;uint32_t q=(uint32_t)t->denominator_u64;putbits(buf,&bit,q-1,b);putbits(buf,&bit,1,1);putbits(buf,&bit,q,b);putbits(buf,&bit,(1u<<b)-1,b);putbits(buf,&bit,0,1);putbits(buf,&bit,0,b);putbits(buf,&bit,0,1);sdat_bitreader r;sdat_bitreader_init(&r,buf,sizeof buf);uint16_t out[2];sdat_stats st;if(frodo_sda_sample_n(out,2,&r,t,&st))return 40+ti;if(st.rejections!=2)return 50+ti;}return 0;}
static int test_bitreader(void){uint8_t buf[80];for(size_t i=0;i<sizeof buf;i++)buf[i]=(uint8_t)(0xa5u+i*13u);for(unsigned pre=0;pre<64;pre++)for(unsigned bits_i=0;bits_i<4;bits_i++){const unsigned bitv[4]={1,7,13,14};unsigned bits=bitv[bits_i];sdat_bitreader r;sdat_bitreader_init(&r,buf,sizeof buf);uint32_t tmp;for(unsigned k=0;k<pre;k++)if(sdat_bitreader_take(&r,1,&tmp))return 60;uint32_t got;if(sdat_bitreader_take(&r,bits,&got))return 61;uint32_t exp=0;for(unsigned j=0;j<bits;j++){size_t p=pre+j;if((buf[p/8]>>(p%8))&1)exp|=1u<<j;}if(got!=exp)return 62;}uint8_t one=0;sdat_bitreader r;sdat_bitreader_init(&r,&one,1);uint32_t x;if(sdat_bitreader_take(&r,14,&x)==0)return 63;return 0;}
static int test_tail(void){uint8_t buf[4096];for(size_t i=0;i<sizeof buf;i++)buf[i]=(uint8_t)(i*37+11);size_t lens[]={0,1,15,16,17,31,32,33,63,64,65};for(int ti=0;ti<3;ti++)for(size_t li=0;li<sizeof(lens)/sizeof(lens[0]);li++){uint16_t a[80],b[80];sdat_bitreader r1,r2;sdat_bitreader_init(&r1,buf,sizeof buf);sdat_bitreader_init(&r2,buf,sizeof buf);if(frodo_sda_sample_n(a,lens[li],&r1,tabs_s[ti],0))return 70;if(frodo_sda_sample_n_avx2(b,lens[li],&r2,tabs_s[ti],0))return 71;if(memcmp(a,b,lens[li]*2))return 72;}return 0;}
int main(void){int r;if((r=test_orig()))return r;if((r=test_sda_map()))return r;if((r=test_reject()))return r;if((r=test_bitreader()))return r;if((r=test_tail()))return r;puts("frodo_sample_n tests passed");return 0;}
