#include "frodo_sample_n.h"
#include "frodo_sample_n_fast.h"
#include "sdat_avx2.h"
#include <stdio.h>
#include <string.h>
static const sdat_table*tabs_o[3]={&original_cdt_table_frodo640,&original_cdt_table_frodo976,&original_cdt_table_frodo1344};
static const sdat_table*tabs_s[3]={&sda_table_frodo640,&sda_table_frodo976,&sda_table_frodo1344};
static uint16_t ref_orig(uint16_t w,const sdat_table*t){const uint16_t*c=t->thresholds;uint16_t m=0,x=w>>1;for(size_t i=0;i<t->threshold_count;i++)m+=(uint16_t)(x>c[i]);return frodo_apply_sign(m,w&1);} 
static int test_orig(void){for(int ti=0;ti<3;ti++){uint16_t a[65536],b[65536];for(unsigned i=0;i<65536;i++)a[i]=b[i]=(uint16_t)i; if(frodo_original_sample_n(a,65536,tabs_o[ti]))return 10+ti; if(frodo_original_sample_n_avx2(b,65536,tabs_o[ti]))return 20+ti; for(unsigned i=0;i<65536;i++)if(a[i]!=ref_orig((uint16_t)i,tabs_o[ti])||b[i]!=a[i])return 30+ti; }return 0;}
static int test_sda_map(void){for(int ti=0;ti<3;ti++){const sdat_table*t=tabs_s[ti];for(uint32_t x=0;x<t->denominator_u64;x++)for(int sg=0;sg<2;sg++){uint16_t r=frodo_apply_sign(frodo_lookup_magnitude_scalar(x,t),(uint8_t)sg);uint16_t r2=r;if(r!=r2)return 1;}}return 0;}
static void putbits(uint8_t*b,size_t*bit,uint32_t v,unsigned bits){for(unsigned i=0;i<bits;i++){if((v>>i)&1)b[*bit/8]|=(uint8_t)(1u<<(*bit%8));(*bit)++;}}
static int test_reject(void){for(int ti=0;ti<3;ti++){const sdat_table*t=tabs_s[ti];uint8_t buf[32]={0};size_t bit=0;unsigned b=t->random_draw_bits;uint32_t q=(uint32_t)t->denominator_u64;putbits(buf,&bit,q-1,b);putbits(buf,&bit,1,1);putbits(buf,&bit,q,b);putbits(buf,&bit,(1u<<b)-1,b);putbits(buf,&bit,0,1);putbits(buf,&bit,0,b);putbits(buf,&bit,0,1);sdat_bitreader r;sdat_bitreader_init(&r,buf,sizeof buf);uint16_t out[2];sdat_stats st;if(frodo_sda_sample_n(out,2,&r,t,&st))return 40+ti;if(st.rejections!=2)return 50+ti;}return 0;}
static int test_bitreader(void){uint8_t buf[80];for(size_t i=0;i<sizeof buf;i++)buf[i]=(uint8_t)(0xa5u+i*13u);for(unsigned pre=0;pre<64;pre++)for(unsigned bits_i=0;bits_i<4;bits_i++){const unsigned bitv[4]={1,7,13,14};unsigned bits=bitv[bits_i];sdat_bitreader r;sdat_bitreader_init(&r,buf,sizeof buf);uint32_t tmp;for(unsigned k=0;k<pre;k++)if(sdat_bitreader_take(&r,1,&tmp))return 60;uint32_t got;if(sdat_bitreader_take(&r,bits,&got))return 61;uint32_t exp=0;for(unsigned j=0;j<bits;j++){size_t p=pre+j;if((buf[p/8]>>(p%8))&1)exp|=1u<<j;}if(got!=exp)return 62;}uint8_t one=0;sdat_bitreader r;sdat_bitreader_init(&r,&one,1);uint32_t x;if(sdat_bitreader_take(&r,14,&x)==0)return 63;return 0;}
static int test_tail(void){uint8_t buf[4096];for(size_t i=0;i<sizeof buf;i++)buf[i]=(uint8_t)(i*37+11);size_t lens[]={0,1,15,16,17,31,32,33,63,64,65};for(int ti=0;ti<3;ti++)for(size_t li=0;li<sizeof(lens)/sizeof(lens[0]);li++){uint16_t a[80],b[80];sdat_bitreader r1,r2;sdat_bitreader_init(&r1,buf,sizeof buf);sdat_bitreader_init(&r2,buf,sizeof buf);if(frodo_sda_sample_n(a,lens[li],&r1,tabs_s[ti],0))return 70;if(frodo_sda_sample_n_avx2(b,lens[li],&r2,tabs_s[ti],0))return 71;if(memcmp(a,b,lens[li]*2))return 72; sdat_bitreader_fast fr; sdat_bitreader_fast_init(&fr,buf,sizeof buf); if(frodo_sda_sample_n_fast(b,lens[li],&fr,tabs_s[ti],0))return 73; if(memcmp(a,b,lens[li]*2))return 74; sdat_bitreader_fast fr2; sdat_bitreader_fast_init(&fr2,buf,sizeof buf); if(frodo_sda_sample_n_fast_avx2(b,lens[li],&fr2,tabs_s[ti],0))return 75; if(memcmp(a,b,lens[li]*2))return 76;}return 0;}

static int test_fast_extract(void){uint8_t buf[96];for(size_t i=0;i<sizeof buf;i++)buf[i]=(uint8_t)(i*19+3);const unsigned bs[4]={1,7,13,14};for(unsigned pre=0;pre<64;pre++)for(unsigned bi=0;bi<4;bi++){sdat_bitreader g;sdat_bitreader_init(&g,buf,sizeof buf);sdat_bitreader_fast f;sdat_bitreader_fast_init(&f,buf,sizeof buf);uint32_t a=0,b=0;for(unsigned k=0;k<pre;k++){if(sdat_bitreader_take(&g,1,&a))return 80;if(sdat_take_1(&f,&b))return 81;}if(sdat_bitreader_take(&g,bs[bi],&a))return 82;int r=(bs[bi]==1)?sdat_take_1(&f,&b):(bs[bi]==7)?sdat_take_7(&f,&b):(bs[bi]==13)?sdat_take_13(&f,&b):sdat_take_14(&f,&b);if(r||a!=b)return 83;}uint8_t seven[7]={0};sdat_bitreader_fast f;sdat_bitreader_fast_init(&f,seven,7);uint32_t x;for(int i=0;i<4;i++)if(sdat_take_14(&f,&x))return 84;return 0;}

static int test_word_sign_exhaustive(void){
 const sdat_table*tabs[3]={&sda_table_frodo640,&sda_table_frodo976,&sda_table_frodo1344};
 unsigned bits[3]={14,13,7}; uint32_t qs[3]={14534,7442,102};
 for(int ti=0;ti<3;ti++){uint64_t s0=0,s1=0,acc=0; for(uint32_t w=0;w<65536;w++){uint32_t c=w&((1u<<bits[ti])-1u); if(c>=qs[ti])continue; uint8_t sign=(uint8_t)((w>>bits[ti])&1u); if(sign)s1++;else s0++;acc++; uint16_t out; uint16_t ww=(uint16_t)w; sdat_stats st; if(frodo_sda_word_sample_n(&out,1,&ww,1,tabs[ti],&st))return 90+ti; uint16_t ref=frodo_apply_sign(frodo_lookup_magnitude_scalar(c,tabs[ti]),sign); if(out!=ref||st.attempts!=1||st.random_bytes!=2)return 100+ti;} if(s0!=s1 || acc!=2ull*qs[ti]*(1ull<<(15-bits[ti])))return 110+ti; }
 return 0;
}

static int test_word_accounting_synthetic(void){
 const sdat_table*tabs[3]={&sda_table_frodo640,&sda_table_frodo976,&sda_table_frodo1344}; unsigned bits[3]={14,13,7}; uint16_t qs[3]={14534,7442,102};
 for(int ti=0;ti<3;ti++){uint16_t words[3];words[0]=qs[ti];words[1]=(uint16_t)((1u<<bits[ti])-1u);words[2]=(uint16_t)(1u<<bits[ti]);uint16_t out=0;sdat_stats st={0};if(frodo_sda_word_sample_n(&out,1,words,3,tabs[ti],&st))return 120+ti;uint64_t logical_candidate=(uint64_t)bits[ti]*st.attempts;uint64_t logical_sign=1;uint64_t logical_used=logical_candidate+logical_sign;uint64_t discarded_sign=st.attempts-1;uint64_t unused=(uint64_t)(16-bits[ti]-1)*st.attempts;uint64_t physical=st.random_bytes*8;if(st.attempts!=3||st.rejections!=2||st.random_bits!=logical_used||physical!=48)return 130+ti;if(logical_used+discarded_sign+unused!=physical)return 140+ti;}
 return 0;
}
int main(void){int r;if((r=test_orig()))return r;if((r=test_sda_map()))return r;if((r=test_reject()))return r;if((r=test_bitreader()))return r;if((r=test_tail()))return r;if((r=test_fast_extract()))return r;if((r=test_word_sign_exhaustive()))return r;if((r=test_word_accounting_synthetic()))return r;puts("frodo_sample_n tests passed");return 0;}
