#include "frodo_sample_n_fast.h"
#include "sdat_tables.h"
#include <string.h>
int frodo1344_sda_word_no_stats_branchless(uint16_t *out,size_t n,const uint16_t *w,size_t wc);
static inline uint16_t sign_sda(uint16_t mag,uint8_t sign){return (uint16_t)(((uint16_t)(-(uint16_t)(sign&1u)) ^ mag) + (sign&1u));}
static inline uint16_t ge640_sda(uint16_t x){const uint16_t*t=sda_table_frodo640.thresholds;return (uint16_t)((x>=t[0])+(x>=t[1])+(x>=t[2])+(x>=t[3])+(x>=t[4])+(x>=t[5])+(x>=t[6])+(x>=t[7])+(x>=t[8])+(x>=t[9])+(x>=t[10]));}
static inline uint16_t ge976_sda(uint16_t x){const uint16_t*t=sda_table_frodo976.thresholds;return (uint16_t)((x>=t[0])+(x>=t[1])+(x>=t[2])+(x>=t[3])+(x>=t[4])+(x>=t[5])+(x>=t[6])+(x>=t[7])+(x>=t[8]));}
static inline uint16_t ge1344_sda(uint8_t x){const uint8_t*t=sda_table_frodo1344.thresholds;return (uint16_t)((x>=t[0])+(x>=t[1])+(x>=t[2])+(x>=t[3]));}
static inline void stat_try(sdat_stats*st,unsigned b,int rej){if(st){st->attempts++;st->random_bits+=b;if(rej)st->rejections++;}}
static inline void stat_sign(sdat_stats*st){if(st)st->random_bits++;}
static inline int next640(sdat_bitreader_fast*r,uint16_t*x,uint8_t*sg,sdat_stats*st){uint32_t v,s;for(;;){if(sdat_take_14(r,&v))return -2; if(v>=14534u){stat_try(st,14,1);continue;} stat_try(st,14,0); if(sdat_take_1(r,&s))return -2; stat_sign(st); *x=(uint16_t)v;*sg=(uint8_t)s;return 0;}}
static inline int next976(sdat_bitreader_fast*r,uint16_t*x,uint8_t*sg,sdat_stats*st){uint32_t v,s;for(;;){if(sdat_take_13(r,&v))return -2; if(v>=7442u){stat_try(st,13,1);continue;} stat_try(st,13,0); if(sdat_take_1(r,&s))return -2; stat_sign(st); *x=(uint16_t)v;*sg=(uint8_t)s;return 0;}}
static inline int next1344(sdat_bitreader_fast*r,uint8_t*x,uint8_t*sg,sdat_stats*st){uint32_t v,s;for(;;){if(sdat_take_7(r,&v))return -2; if(v>=102u){stat_try(st,7,1);continue;} stat_try(st,7,0); if(sdat_take_1(r,&s))return -2; stat_sign(st); *x=(uint8_t)v;*sg=(uint8_t)s;return 0;}}
#define FINISH_STATS() do{if(st)st->random_bytes=r->bytes_loaded;}while(0)
int frodo640_sda_sample_n_scalar(uint16_t*out,size_t n,sdat_bitreader_fast*r,sdat_stats*st){if(st)*st=(sdat_stats){0}; for(size_t i=0;i<n;i++){uint16_t x;uint8_t s;if(next640(r,&x,&s,st))return -2;out[i]=sign_sda(ge640_sda(x),s);} FINISH_STATS(); return 0;}
int frodo976_sda_sample_n_scalar(uint16_t*out,size_t n,sdat_bitreader_fast*r,sdat_stats*st){if(st)*st=(sdat_stats){0}; for(size_t i=0;i<n;i++){uint16_t x;uint8_t s;if(next976(r,&x,&s,st))return -2;out[i]=sign_sda(ge976_sda(x),s);} FINISH_STATS(); return 0;}
int frodo1344_sda_sample_n_scalar(uint16_t*out,size_t n,sdat_bitreader_fast*r,sdat_stats*st){if(st)*st=(sdat_stats){0}; for(size_t i=0;i<n;i++){uint8_t x,s;if(next1344(r,&x,&s,st))return -2;out[i]=sign_sda(ge1344_sda(x),s);} FINISH_STATS(); return 0;}
int frodo_sda_sample_n_fast(uint16_t*out,size_t n,sdat_bitreader_fast*r,const sdat_table*t,sdat_stats*st){if(!out||!r||!t)return -1;if(t==&sda_table_frodo640)return frodo640_sda_sample_n_scalar(out,n,r,st);if(t==&sda_table_frodo976)return frodo976_sda_sample_n_scalar(out,n,r,st);if(t==&sda_table_frodo1344)return frodo1344_sda_sample_n_scalar(out,n,r,st);return -3;}
/* Word-oriented profile: a uniform 16-bit word supplies both fields.
 * candidate = low b bits; sign = bit b. Rejection depends only on low b bits,
 * so conditioning on acceptance leaves bit b uniform and independent. */
static inline int frodo640_word_next(const uint16_t*w,size_t wc,size_t*p,uint16_t*x,uint8_t*sg,sdat_stats*st){for(;;){if(*p>=wc)return -2;uint16_t z=w[(*p)++];uint16_t c=z&0x3fffu;if(st){st->attempts++;st->random_bits+=14;st->random_bytes=(*p)*2;if(c>=14534u)st->rejections++;}if(c>=14534u)continue;if(st)st->random_bits+=1;*x=c;*sg=(uint8_t)((z>>14)&1u);return 0;}}
static inline int frodo976_word_next(const uint16_t*w,size_t wc,size_t*p,uint16_t*x,uint8_t*sg,sdat_stats*st){for(;;){if(*p>=wc)return -2;uint16_t z=w[(*p)++];uint16_t c=z&0x1fffu;if(st){st->attempts++;st->random_bits+=13;st->random_bytes=(*p)*2;if(c>=7442u)st->rejections++;}if(c>=7442u)continue;if(st)st->random_bits+=1;*x=c;*sg=(uint8_t)((z>>13)&1u);return 0;}}
static inline int frodo1344_word_next(const uint16_t*w,size_t wc,size_t*p,uint8_t*x,uint8_t*sg,sdat_stats*st){for(;;){if(*p>=wc)return -2;uint16_t z=w[(*p)++];uint8_t c=(uint8_t)(z&0x7fu);if(st){st->attempts++;st->random_bits+=7;st->random_bytes=(*p)*2;if(c>=102u)st->rejections++;}if(c>=102u)continue;if(st)st->random_bits+=1;*x=c;*sg=(uint8_t)((z>>7)&1u);return 0;}}
static int word640_no_stats(uint16_t*out,size_t n,const uint16_t*w,size_t wc){const uint16_t*src=w,*end=w+wc;uint16_t*dst=out,*dst_end=out+n;while(dst<dst_end){uint16_t z,c;do{if(src>=end)return -2;z=*src++;c=(uint16_t)(z&0x3fffu);}while(c>=14534u);*dst++=sign_sda(ge640_sda(c),(uint8_t)((z>>14)&1u));}return 0;}
static int word976_no_stats(uint16_t*out,size_t n,const uint16_t*w,size_t wc){const uint16_t*src=w,*end=w+wc;uint16_t*dst=out,*dst_end=out+n;while(dst<dst_end){uint16_t z,c;do{if(src>=end)return -2;z=*src++;c=(uint16_t)(z&0x1fffu);}while(c>=7442u);*dst++=sign_sda(ge976_sda(c),(uint8_t)((z>>13)&1u));}return 0;}
static int word640_with_stats(uint16_t*out,size_t n,const uint16_t*w,size_t wc,sdat_stats*st){size_t p=0;*st=(sdat_stats){0};for(size_t i=0;i<n;i++){uint16_t x;uint8_t s;if(frodo640_word_next(w,wc,&p,&x,&s,st))return -2;out[i]=sign_sda(ge640_sda(x),s);}return 0;}
static int word976_with_stats(uint16_t*out,size_t n,const uint16_t*w,size_t wc,sdat_stats*st){size_t p=0;*st=(sdat_stats){0};for(size_t i=0;i<n;i++){uint16_t x;uint8_t s;if(frodo976_word_next(w,wc,&p,&x,&s,st))return -2;out[i]=sign_sda(ge976_sda(x),s);}return 0;}
static int word1344_with_stats(uint16_t*out,size_t n,const uint16_t*w,size_t wc,sdat_stats*st){size_t p=0;*st=(sdat_stats){0};for(size_t i=0;i<n;i++){uint8_t x,s;if(frodo1344_word_next(w,wc,&p,&x,&s,st))return -2;out[i]=sign_sda(ge1344_sda(x),s);}return 0;}
static int word640(uint16_t*out,size_t n,const uint16_t*w,size_t wc,sdat_stats*st){return st?word640_with_stats(out,n,w,wc,st):word640_no_stats(out,n,w,wc);}
static int word976(uint16_t*out,size_t n,const uint16_t*w,size_t wc,sdat_stats*st){return st?word976_with_stats(out,n,w,wc,st):word976_no_stats(out,n,w,wc);}
static int word1344(uint16_t*out,size_t n,const uint16_t*w,size_t wc,sdat_stats*st){return st?word1344_with_stats(out,n,w,wc,st):frodo1344_sda_word_no_stats_branchless(out,n,w,wc);}
int frodo_sda_word_sample_n(uint16_t*out,size_t n,const uint16_t*w,size_t wc,const sdat_table*t,sdat_stats*st){if(t==&sda_table_frodo640)return word640(out,n,w,wc,st);if(t==&sda_table_frodo976)return word976(out,n,w,wc,st);if(t==&sda_table_frodo1344)return word1344(out,n,w,wc,st);return -1;}
int frodo_sda_word_sample_n_avx2(uint16_t*out,size_t n,const uint16_t*w,size_t wc,const sdat_table*t,sdat_stats*st){return frodo_sda_word_sample_n(out,n,w,wc,t,st);} 
