#include "frodo_sample_n_fast.h"
#include "sdat_tables.h"
#include <string.h>
static inline uint16_t ge16(uint16_t x,const uint16_t*t,size_t n){uint16_t r=0;for(size_t i=0;i<n;i++)r+=(uint16_t)(x>=t[i]);return r;}
static inline uint16_t ge8(uint8_t x,const uint8_t*t,size_t n){uint16_t r=0;for(size_t i=0;i<n;i++)r+=(uint16_t)(x>=t[i]);return r;}
static inline void stat_try(sdat_stats*st,unsigned b,int rej){if(st){st->attempts++;st->random_bits+=b;if(rej)st->rejections++;}}
static inline void stat_sign(sdat_stats*st){if(st)st->random_bits++;}
static inline int next640(sdat_bitreader_fast*r,uint16_t*x,uint8_t*sg,sdat_stats*st){uint32_t v,s;for(;;){if(sdat_take_14(r,&v))return -2; if(v>=14534u){stat_try(st,14,1);continue;} stat_try(st,14,0); if(sdat_take_1(r,&s))return -2; stat_sign(st); *x=(uint16_t)v;*sg=(uint8_t)s;return 0;}}
static inline int next976(sdat_bitreader_fast*r,uint16_t*x,uint8_t*sg,sdat_stats*st){uint32_t v,s;for(;;){if(sdat_take_13(r,&v))return -2; if(v>=7442u){stat_try(st,13,1);continue;} stat_try(st,13,0); if(sdat_take_1(r,&s))return -2; stat_sign(st); *x=(uint16_t)v;*sg=(uint8_t)s;return 0;}}
static inline int next1344(sdat_bitreader_fast*r,uint8_t*x,uint8_t*sg,sdat_stats*st){uint32_t v,s;for(;;){if(sdat_take_7(r,&v))return -2; if(v>=102u){stat_try(st,7,1);continue;} stat_try(st,7,0); if(sdat_take_1(r,&s))return -2; stat_sign(st); *x=(uint8_t)v;*sg=(uint8_t)s;return 0;}}
#define FINISH_STATS() do{if(st)st->random_bytes=r->bytes_loaded;}while(0)
int frodo640_sda_sample_n_scalar(uint16_t*out,size_t n,sdat_bitreader_fast*r,sdat_stats*st){const uint16_t*thr= sda_table_frodo640.thresholds; if(st)*st=(sdat_stats){0}; for(size_t i=0;i<n;i++){uint16_t x;uint8_t s;if(next640(r,&x,&s,st))return -2;out[i]=frodo_apply_sign(ge16(x,thr,11),s);} FINISH_STATS(); return 0;}
int frodo976_sda_sample_n_scalar(uint16_t*out,size_t n,sdat_bitreader_fast*r,sdat_stats*st){const uint16_t*thr=sda_table_frodo976.thresholds; if(st)*st=(sdat_stats){0}; for(size_t i=0;i<n;i++){uint16_t x;uint8_t s;if(next976(r,&x,&s,st))return -2;out[i]=frodo_apply_sign(ge16(x,thr,9),s);} FINISH_STATS(); return 0;}
int frodo1344_sda_sample_n_scalar(uint16_t*out,size_t n,sdat_bitreader_fast*r,sdat_stats*st){const uint8_t*thr=sda_table_frodo1344.thresholds; if(st)*st=(sdat_stats){0}; for(size_t i=0;i<n;i++){uint8_t x,s;if(next1344(r,&x,&s,st))return -2;out[i]=frodo_apply_sign(ge8(x,thr,4),s);} FINISH_STATS(); return 0;}
int frodo_sda_sample_n_fast(uint16_t*out,size_t n,sdat_bitreader_fast*r,const sdat_table*t,sdat_stats*st){if(!out||!r||!t)return -1;if(t==&sda_table_frodo640)return frodo640_sda_sample_n_scalar(out,n,r,st);if(t==&sda_table_frodo976)return frodo976_sda_sample_n_scalar(out,n,r,st);if(t==&sda_table_frodo1344)return frodo1344_sda_sample_n_scalar(out,n,r,st);return -3;}
/* Word-oriented profile: a uniform 16-bit word supplies both fields.
 * candidate = low b bits; sign = bit b. Rejection depends only on low b bits,
 * so conditioning on acceptance leaves bit b uniform and independent. */
static inline int frodo640_word_next(const uint16_t*w,size_t wc,size_t*p,uint16_t*x,uint8_t*sg,sdat_stats*st){for(;;){if(*p>=wc)return -2;uint16_t z=w[(*p)++];uint16_t c=z&0x3fffu;if(st){st->attempts++;st->random_bits+=14;st->random_bytes=(*p)*2;if(c>=14534u)st->rejections++;}if(c>=14534u)continue;if(st)st->random_bits+=1;*x=c;*sg=(uint8_t)((z>>14)&1u);return 0;}}
static inline int frodo976_word_next(const uint16_t*w,size_t wc,size_t*p,uint16_t*x,uint8_t*sg,sdat_stats*st){for(;;){if(*p>=wc)return -2;uint16_t z=w[(*p)++];uint16_t c=z&0x1fffu;if(st){st->attempts++;st->random_bits+=13;st->random_bytes=(*p)*2;if(c>=7442u)st->rejections++;}if(c>=7442u)continue;if(st)st->random_bits+=1;*x=c;*sg=(uint8_t)((z>>13)&1u);return 0;}}
static inline int frodo1344_word_next(const uint16_t*w,size_t wc,size_t*p,uint8_t*x,uint8_t*sg,sdat_stats*st){for(;;){if(*p>=wc)return -2;uint16_t z=w[(*p)++];uint8_t c=(uint8_t)(z&0x7fu);if(st){st->attempts++;st->random_bits+=7;st->random_bytes=(*p)*2;if(c>=102u)st->rejections++;}if(c>=102u)continue;if(st)st->random_bits+=1;*x=c;*sg=(uint8_t)((z>>7)&1u);return 0;}}
static int word640(uint16_t*out,size_t n,const uint16_t*w,size_t wc,sdat_stats*st){const uint16_t*thr=sda_table_frodo640.thresholds;size_t p=0;if(st)*st=(sdat_stats){0};for(size_t i=0;i<n;i++){uint16_t x;uint8_t s;if(frodo640_word_next(w,wc,&p,&x,&s,st))return -2;out[i]=frodo_apply_sign(ge16(x,thr,11),s);}return 0;}
static int word976(uint16_t*out,size_t n,const uint16_t*w,size_t wc,sdat_stats*st){const uint16_t*thr=sda_table_frodo976.thresholds;size_t p=0;if(st)*st=(sdat_stats){0};for(size_t i=0;i<n;i++){uint16_t x;uint8_t s;if(frodo976_word_next(w,wc,&p,&x,&s,st))return -2;out[i]=frodo_apply_sign(ge16(x,thr,9),s);}return 0;}
static int word1344(uint16_t*out,size_t n,const uint16_t*w,size_t wc,sdat_stats*st){const uint8_t*thr=sda_table_frodo1344.thresholds;size_t p=0;if(st)*st=(sdat_stats){0};for(size_t i=0;i<n;i++){uint8_t x,s;if(frodo1344_word_next(w,wc,&p,&x,&s,st))return -2;out[i]=frodo_apply_sign(ge8(x,thr,4),s);}return 0;}
int frodo_sda_word_sample_n(uint16_t*out,size_t n,const uint16_t*w,size_t wc,const sdat_table*t,sdat_stats*st){if(t==&sda_table_frodo640)return word640(out,n,w,wc,st);if(t==&sda_table_frodo976)return word976(out,n,w,wc,st);if(t==&sda_table_frodo1344)return word1344(out,n,w,wc,st);return -1;}
int frodo_sda_word_sample_n_avx2(uint16_t*out,size_t n,const uint16_t*w,size_t wc,const sdat_table*t,sdat_stats*st){return frodo_sda_word_sample_n(out,n,w,wc,t,st);} 
