#include "frodo_sample_n.h"
static inline uint16_t look_u16_ge(uint16_t x,const uint16_t*t,size_t n){uint16_t r=0;for(size_t i=0;i<n;i++)r+=(uint16_t)(x>=t[i]);return r;}
static inline uint16_t look_u8_ge(uint8_t x,const uint8_t*t,size_t n){uint16_t r=0;for(size_t i=0;i<n;i++)r+=(uint16_t)(x>=t[i]);return r;}
static inline uint16_t look_official(uint16_t x,const uint16_t*t,size_t n){uint16_t r=0;for(size_t i=0;i<n;i++)r+=(uint16_t)(x>t[i]);return r;}

static inline uint16_t look_orig640(uint16_t x){const uint16_t*t=(const uint16_t*)original_cdt_table_frodo640.thresholds;return (uint16_t)((x>t[0])+(x>t[1])+(x>t[2])+(x>t[3])+(x>t[4])+(x>t[5])+(x>t[6])+(x>t[7])+(x>t[8])+(x>t[9])+(x>t[10])+(x>t[11])+(x>t[12]));}
static inline uint16_t look_orig976(uint16_t x){const uint16_t*t=(const uint16_t*)original_cdt_table_frodo976.thresholds;return (uint16_t)((x>t[0])+(x>t[1])+(x>t[2])+(x>t[3])+(x>t[4])+(x>t[5])+(x>t[6])+(x>t[7])+(x>t[8])+(x>t[9])+(x>t[10]));}
static inline uint16_t look_orig1344(uint16_t x){const uint16_t*t=(const uint16_t*)original_cdt_table_frodo1344.thresholds;return (uint16_t)((x>t[0])+(x>t[1])+(x>t[2])+(x>t[3])+(x>t[4])+(x>t[5])+(x>t[6]));}
uint16_t frodo_apply_sign(uint16_t mag,uint8_t sign){return (uint16_t)(((uint16_t)(-(uint16_t)(sign&1u)) ^ mag) + (sign&1u));}
uint16_t frodo_lookup_magnitude_scalar(uint32_t x,const sdat_table*t){ if(t->value_type==SDAT_TYPE_U8)return look_u8_ge((uint8_t)x,(const uint8_t*)t->thresholds,t->threshold_count); return look_u16_ge((uint16_t)x,(const uint16_t*)t->thresholds,t->threshold_count); }
int frodo_original_sample_n(uint16_t*s,size_t n,const sdat_table*t){ if(!s||!t||t->value_type!=SDAT_TYPE_U16)return -1; if(t==&original_cdt_table_frodo640){for(size_t i=0;i<n;i++){uint16_t w=s[i];s[i]=frodo_apply_sign(look_orig640((uint16_t)(w>>1)),(uint8_t)(w&1));}return 0;} if(t==&original_cdt_table_frodo976){for(size_t i=0;i<n;i++){uint16_t w=s[i];s[i]=frodo_apply_sign(look_orig976((uint16_t)(w>>1)),(uint8_t)(w&1));}return 0;} if(t==&original_cdt_table_frodo1344){for(size_t i=0;i<n;i++){uint16_t w=s[i];s[i]=frodo_apply_sign(look_orig1344((uint16_t)(w>>1)),(uint8_t)(w&1));}return 0;} const uint16_t*thr=(const uint16_t*)t->thresholds; size_t tn=t->threshold_count; for(size_t i=0;i<n;i++){uint16_t w=s[i]; uint16_t mag=look_official((uint16_t)(w>>1),thr,tn); s[i]=frodo_apply_sign(mag,(uint8_t)(w&1));} return 0; }
static size_t uni16(sdat_bitreader*r,uint16_t q,unsigned bits,uint16_t*a,uint8_t*sg,size_t target,sdat_stats*st){size_t k=0; while(k<target){uint32_t x,sign;if(sdat_bitreader_take(r,bits,&x))break; if(st){st->attempts++;st->random_bits+=bits;} if(x>=q){if(st)st->rejections++; continue;} if(sdat_bitreader_take(r,1,&sign))break; if(st)st->random_bits+=1; a[k]=(uint16_t)x; sg[k]=(uint8_t)(sign&1); k++;} if(st)st->random_bytes=sdat_bitreader_source_bytes_consumed(r); return k;}
static size_t uni8(sdat_bitreader*r,uint8_t q,unsigned bits,uint8_t*a,uint8_t*sg,size_t target,sdat_stats*st){size_t k=0; while(k<target){uint32_t x,sign;if(sdat_bitreader_take(r,bits,&x))break; if(st){st->attempts++;st->random_bits+=bits;} if(x>=q){if(st)st->rejections++; continue;} if(sdat_bitreader_take(r,1,&sign))break; if(st)st->random_bits+=1; a[k]=(uint8_t)x; sg[k]=(uint8_t)(sign&1); k++;} if(st)st->random_bytes=sdat_bitreader_source_bytes_consumed(r); return k;}
size_t frodo_uniform_bounded_u16_batch(sdat_bitreader*r,uint16_t q,unsigned bits,uint16_t*a,uint8_t*s,size_t target,sdat_stats*st){return uni16(r,q,bits,a,s,target,st);} 
size_t frodo_uniform_bounded_u8_batch(sdat_bitreader*r,uint8_t q,unsigned bits,uint8_t*a,uint8_t*s,size_t target,sdat_stats*st){return uni8(r,q,bits,a,s,target,st);} 
int frodo_sda_sample_n(uint16_t*out,size_t n,sdat_bitreader*r,const sdat_table*t,sdat_stats*st){ if(!out||!r||!t)return -1; if(st)*st=(sdat_stats){0,0,0,0}; if(t->value_type==SDAT_TYPE_U16){const uint16_t*thr=t->thresholds; uint16_t q=(uint16_t)t->denominator_u64; unsigned bits=t->random_draw_bits; for(size_t i=0;i<n;i++){uint16_t x;uint8_t sign; if(uni16(r,q,bits,&x,&sign,1,st)!=1)return -2; out[i]=frodo_apply_sign(look_u16_ge(x,thr,t->threshold_count),sign);} return 0;} if(t->value_type==SDAT_TYPE_U8){const uint8_t*thr=t->thresholds; uint8_t q=(uint8_t)t->denominator_u64; unsigned bits=t->random_draw_bits; for(size_t i=0;i<n;i++){uint8_t x,sign; if(uni8(r,q,bits,&x,&sign,1,st)!=1)return -2; out[i]=frodo_apply_sign(look_u8_ge(x,thr,t->threshold_count),sign);} return 0;} return -3;}
