#include "frodo_sample_n_fast.h"
#include "sdat_tables.h"
#include <string.h>
static inline uint16_t ge16(uint16_t x,const uint16_t*t,size_t n){uint16_t r=0;for(size_t i=0;i<n;i++)r+=(uint16_t)(x>=t[i]);return r;}
static inline uint16_t ge8(uint8_t x,const uint8_t*t,size_t n){uint16_t r=0;for(size_t i=0;i<n;i++)r+=(uint16_t)(x>=t[i]);return r;}
static inline void stat_try(sdat_stats*st,unsigned b,int rej){if(st){st->attempts++;st->random_bits+=b;if(rej)st->rejections++;}}
static inline void stat_sign(sdat_stats*st){if(st)st->random_bits++;}
static inline int next640(sdat_bitreader_fast*r,uint16_t*x,uint8_t*sg,sdat_stats*st){uint32_t v,s;for(;;){if(sdat_take_14(r,&v))return -2; if(v>=14534u){stat_try(st,14,1);continue;} stat_try(st,14,0); if(sdat_take_1(r,&s))return -2; stat_sign(st); *x=(uint16_t)v;*sg=(uint8_t)s;return 0;}}
static inline int next976(sdat_bitreader_fast*r,uint16_t*x,uint8_t*sg,sdat_stats*st){uint32_t v,s;for(;;){if(sdat_take_13(r,&v))return -2; if(v>=7442u){stat_try(st,13,1);continue;} stat_try(st,13,0); if(sdat_take_1(r,&s))return -2; stat_sign(st); *x=(uint16_t)v;*sg=(uint8_t)s;return 0;}}
static inline int next1344(sdat_bitreader_fast*r,uint8_t*x,uint8_t*sg,sdat_stats*st){uint32_t v,s;for(;;){if(sdat_take_7(r,&v))return -2; if(v>=102u){stat_try(st,7,1);continue;} stat_try(st,7,0); if(sdat_take_1(r,&s))return -2; stat_sign(st); *x=(uint8_t)v;*sg=(uint8_t)s;return 0;}}
#define FINISH_STATS() do{if(st)st->random_bytes=r->bytes_loaded;}while(0)
int frodo640_sda_sample_n_scalar(uint16_t*out,size_t n,sdat_bitreader_fast*r,sdat_stats*st){const uint16_t*thr= sda_table_frodo640.thresholds; if(st)*st=(sdat_stats){0}; for(size_t i=0;i<n;i++){uint16_t x;uint8_t s;if(next640(r,&x,&s,st))return -2;out[i]=frodo_apply_sign(ge16(x,thr,11),s);} FINISH_STATS(); return 0;}
int frodo976_sda_sample_n_scalar(uint16_t*out,size_t n,sdat_bitreader_fast*r,sdat_stats*st){const uint16_t*thr=sda_table_frodo976.thresholds; if(st)*st=(sdat_stats){0}; for(size_t i=0;i<n;i++){uint16_t x;uint8_t s;if(next976(r,&x,&s,st))return -2;out[i]=frodo_apply_sign(ge16(x,thr,9),s);} FINISH_STATS(); return 0;}
int frodo1344_sda_sample_n_scalar(uint16_t*out,size_t n,sdat_bitreader_fast*r,sdat_stats*st){const uint8_t*thr=sda_table_frodo1344.thresholds; if(st)*st=(sdat_stats){0}; for(size_t i=0;i<n;i++){uint8_t x,s;if(next1344(r,&x,&s,st))return -2;out[i]=frodo_apply_sign(ge8(x,thr,4),s);} FINISH_STATS(); return 0;}
int frodo_sda_sample_n_fast(uint16_t*out,size_t n,sdat_bitreader_fast*r,const sdat_table*t,sdat_stats*st){if(!out||!r||!t)return -1;if(t==&sda_table_frodo640)return frodo640_sda_sample_n_scalar(out,n,r,st);if(t==&sda_table_frodo976)return frodo976_sda_sample_n_scalar(out,n,r,st);if(t==&sda_table_frodo1344)return frodo1344_sda_sample_n_scalar(out,n,r,st);return -3;}
static int word_u16(uint16_t*out,size_t n,const uint16_t*w,size_t wc,const uint16_t*thr,size_t tn,uint16_t q,unsigned bits,sdat_stats*st){size_t p=0;uint16_t mask=(uint16_t)((1u<<bits)-1u);if(st)*st=(sdat_stats){0};for(size_t i=0;i<n;i++){uint16_t x;do{if(p>=wc)return -2;x=w[p++]&mask;if(st){st->attempts++;st->random_bits+=bits;st->random_bytes=p*2;if(x>=q)st->rejections++;}}while(x>=q); if(p>=wc)return -2;uint8_t s=(uint8_t)(w[p++]&1u);if(st){st->random_bits++;st->random_bytes=p*2;}out[i]=frodo_apply_sign(ge16(x,thr,tn),s);}return 0;}
static int word_u8(uint16_t*out,size_t n,const uint16_t*w,size_t wc,const uint8_t*thr,size_t tn,uint8_t q,unsigned bits,sdat_stats*st){size_t p=0;uint16_t mask=(uint16_t)((1u<<bits)-1u);if(st)*st=(sdat_stats){0};for(size_t i=0;i<n;i++){uint8_t x;uint16_t v;do{if(p>=wc)return -2;v=w[p++]&mask;x=(uint8_t)v;if(st){st->attempts++;st->random_bits+=bits;st->random_bytes=p*2;if(x>=q)st->rejections++;}}while(x>=q); if(p>=wc)return -2;uint8_t s=(uint8_t)(w[p++]&1u);if(st){st->random_bits++;st->random_bytes=p*2;}out[i]=frodo_apply_sign(ge8(x,thr,tn),s);}return 0;}
int frodo_sda_word_sample_n(uint16_t*out,size_t n,const uint16_t*w,size_t wc,const sdat_table*t,sdat_stats*st){if(t==&sda_table_frodo640)return word_u16(out,n,w,wc,sda_table_frodo640.thresholds,11,14534,14,st);if(t==&sda_table_frodo976)return word_u16(out,n,w,wc,sda_table_frodo976.thresholds,9,7442,13,st);if(t==&sda_table_frodo1344)return word_u8(out,n,w,wc,sda_table_frodo1344.thresholds,4,102,7,st);return -1;}
int frodo_sda_word_sample_n_avx2(uint16_t*out,size_t n,const uint16_t*w,size_t wc,const sdat_table*t,sdat_stats*st){return frodo_sda_word_sample_n(out,n,w,wc,t,st);} 
