#include "sdat_ref.h"
static void addst(sdat_stats*st,unsigned bytes,unsigned bits,int rej){ if(st){st->attempts++;st->random_bytes+=bytes;st->random_bits+=bits;if(rej)st->rejections++;}}
uint32_t online_lookup_u8(uint8_t x,const uint8_t*t,size_t n){uint32_t j=0;for(size_t i=0;i<n;i++)j+=(uint32_t)(x>=t[i]);return j;}
uint32_t online_lookup_u16(uint16_t x,const uint16_t*t,size_t n){uint32_t j=0;for(size_t i=0;i<n;i++)j+=(uint32_t)(x>=t[i]);return j;}
uint32_t online_lookup_u72(sdat_u72 x,const sdat_u72*t,size_t n){uint32_t j=0;for(size_t i=0;i<n;i++)j+=(uint32_t)sdat_u72_ge(x,t[i]);return j;}
uint32_t online_lookup_u72_reverse_tail(sdat_u72 x,const sdat_u72*t,size_t n){uint32_t j=0;for(size_t i=0;i<n;i++)j+=(uint32_t)sdat_u72_lt(x,t[i]);return j;}
static int draw_bits_u8(unsigned bits,sdat_randombytes_fn fn,void*ctx,uint8_t*out,sdat_stats*st){ if(!fn||!out||bits>8)return -1; uint8_t b; if(fn(ctx,&b,1))return -2; b&=(uint8_t)((1u<<bits)-1u); *out=b; addst(st,1,bits,0); return 0;}
static int draw_bits_u16(unsigned bits,sdat_randombytes_fn fn,void*ctx,uint16_t*out,sdat_stats*st){ if(!fn||!out||bits>16)return -1; uint8_t b[2]; if(fn(ctx,b,2))return -2; uint16_t mask=(bits==16)?65535u:(uint16_t)((1u<<bits)-1u); *out=(uint16_t)(b[0]|((uint16_t)b[1]<<8)); *out&=mask; addst(st,2,bits,0); return 0;}
static int uniform_u8(uint8_t q,unsigned bits,sdat_randombytes_fn fn,void*ctx,uint8_t*out,sdat_stats*st){ uint8_t x; int r; do{r=draw_bits_u8(bits,fn,ctx,&x,st); if(r)return r; if(x>=q && st)st->rejections++;}while(x>=q); *out=x; return 0;}
static int uniform_u16(uint16_t q,unsigned bits,sdat_randombytes_fn fn,void*ctx,uint16_t*out,sdat_stats*st){ uint16_t x; int r; do{r=draw_bits_u16(bits,fn,ctx,&x,st); if(r)return r; if(x>=q && st)st->rejections++;}while(x>=q); *out=x; return 0;}
static int uniform_u72(sdat_u72 q,sdat_randombytes_fn fn,void*ctx,sdat_u72*out,sdat_stats*st){ if(!fn||!out)return -1; uint8_t b[9]; sdat_u72 x; do{ if(fn(ctx,b,9))return -2; x=sdat_u72_from_le9(b); addst(st,9,72,sdat_u72_ge(x,q)); }while(sdat_u72_ge(x,q)); *out=x; return 0;}
int original_cdt_ref_sample(const sdat_table*t,sdat_randombytes_fn fn,void*ctx,uint32_t*out,sdat_stats*st){ if(!t||!out||!t->available)return -1; if(t->value_type==SDAT_TYPE_U8){uint8_t x; int r=uniform_u8((uint8_t)t->denominator_u64,t->random_draw_bits,fn,ctx,&x,st); if(r)return r; *out=online_lookup_u8(x,(const uint8_t*)t->thresholds,t->threshold_count); return 0;} if(t->value_type==SDAT_TYPE_U16){uint16_t x; int r=draw_bits_u16(t->random_draw_bits,fn,ctx,&x,st); if(r)return r; *out=online_lookup_u16(x,(const uint16_t*)t->thresholds,t->threshold_count); return 0;} if(t->value_type==SDAT_TYPE_U72){uint8_t b[9]; if(fn(ctx,b,9))return -2; addst(st,9,72,0); sdat_u72 x=sdat_u72_from_le9(b); *out=online_lookup_u72_reverse_tail(x,(const sdat_u72*)t->thresholds,t->threshold_count); return 0;} return -3;}
int original_cdt_ref_sample_batch(const sdat_table*t,sdat_randombytes_fn fn,void*ctx,uint32_t*out,size_t n,sdat_stats*st){ if(n==0)return 0; if(!out)return -1; for(size_t i=0;i<n;i++){int r=original_cdt_ref_sample(t,fn,ctx,&out[i],st); if(r)return r;} return 0;}
int sda_cdt_ref_sample(const sdat_table*t,sdat_randombytes_fn fn,void*ctx,uint32_t*out,sdat_stats*st){ if(!t||!out||!t->available)return -1; if(t->value_type==SDAT_TYPE_U8){uint8_t x; int r=uniform_u8((uint8_t)t->denominator_u64,t->random_draw_bits,fn,ctx,&x,st); if(r)return r; *out=online_lookup_u8(x,(const uint8_t*)t->thresholds,t->threshold_count); return 0;} if(t->value_type==SDAT_TYPE_U16){uint16_t x; int r=uniform_u16((uint16_t)t->denominator_u64,t->random_draw_bits,fn,ctx,&x,st); if(r)return r; *out=online_lookup_u16(x,(const uint16_t*)t->thresholds,t->threshold_count); return 0;} if(t->value_type==SDAT_TYPE_U72){sdat_u72 x; int r=uniform_u72(t->denominator_u72,fn,ctx,&x,st); if(r)return r; *out=online_lookup_u72(x,(const sdat_u72*)t->thresholds,t->threshold_count); return 0;} return -3;}
int sda_cdt_ref_sample_batch(const sdat_table*t,sdat_randombytes_fn fn,void*ctx,uint32_t*out,size_t n,sdat_stats*st){ if(n==0)return 0; if(!out)return -1; for(size_t i=0;i<n;i++){int r=sda_cdt_ref_sample(t,fn,ctx,&out[i],st); if(r)return r;} return 0;}
int sdat_ref_sample(const sdat_table*t,sdat_randombytes_fn fn,void*ctx,uint32_t*out){return sda_cdt_ref_sample(t,fn,ctx,out,0);} 
int sdat_ref_sample_batch(const sdat_table*t,sdat_randombytes_fn fn,void*ctx,uint32_t*out,size_t n){return sda_cdt_ref_sample_batch(t,fn,ctx,out,n,0);} 
