#include <stdio.h>
#include "sda_falcon_bkz.h"
#include <gmp.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdlib.h>
static sda_u128 get128(const mpz_t z){unsigned char b[16]={0};size_t n=0;mpz_export(b,&n,-1,1,0,0,z);sda_u128 x=0;for(size_t i=0;i<n&&i<16;i++)x|=(sda_u128)b[i]<<(8*i);return x;}
int sda_falcon_bkz_available(char*v,size_t n){FILE*p=popen("fplll --version 2>&1","r");if(!p)return 0;int ok=fgets(v,(int)n,p)!=0;char discard[256];while(fgets(discard,sizeof discard,p)){}int st=pclose(p);if(!ok||st){if(n)v[0]=0;return 0;}v[strcspn(v,"\r\n")]=0;return 1;}
int sda_falcon_basis_write(FILE*f,mpfr_t*a,mpfr_t eps,mpfr_prec_t pr,mpz_t D,mpz_t A[19]){mpfr_t x;mpfr_init2(x,pr);mpfr_ui_div(x,1,eps,MPFR_RNDN);mpfr_pow_ui(x,x,20,MPFR_RNDN);mpfr_get_z(D,x,MPFR_RNDN);if(mpz_sgn(D)<=0)mpz_set_ui(D,1);for(int i=0;i<19;i++){mpfr_mul_z(x,a[i],D,MPFR_RNDN);mpfr_neg(x,x,MPFR_RNDN);mpfr_get_z(A[i],x,MPFR_RNDN);}fputs("[\n",f);for(int i=0;i<19;i++){fputc('[',f);for(int j=0;j<20;j++){if(j)fputc(' ',f);if(i==j)mpz_out_str(f,10,D);else fputc('0',f);}fputs("]\n",f);}fputc('[',f);for(int i=0;i<19;i++){if(i)fputc(' ',f);mpz_out_str(f,10,A[i]);}fputs(" 1]\n]\n",f);mpfr_clear(x);return ferror(f)?-1:0;}
int sda_falcon_recover(const mpz_t*row,const mpz_t D,const mpz_t A[19],sda_falcon_bkz_result*r){mpz_t q,num,rem;mpz_inits(q,num,rem,NULL);mpz_set(q,row[19]);int sign=mpz_sgn(q)<0?-1:1;if(sign<0)mpz_neg(q,q);if(mpz_sgn(q)<=0||mpz_sizeinbase(q,2)>128){mpz_clears(q,num,rem,NULL);return-1;}r->q=get128(q);for(int i=0;i<19;i++){mpz_mul(num,row[19],A[i]);mpz_sub(num,row[i],num);mpz_tdiv_qr(num,rem,num,D);if(mpz_sgn(rem)){mpz_clears(q,num,rem,NULL);return-2;}if(sign<0)mpz_neg(num,num);if(mpz_sgn(num)<0||mpz_sizeinbase(num,2)>128){mpz_clears(q,num,rem,NULL);return-3;}r->p[i]=get128(num);}mpz_clears(q,num,rem,NULL);return 0;}
static int parse_line(char*line,mpz_t row[20]){char*p=strchr(line,91);if(!p)return-1;p++;for(int i=0;i<20;i++){while(*p==32||*p==9)p++;char*e=p;while(*e&&*e!=32&&*e!=9&&*e!=93&&*e!=10)e++;char save=*e;*e=0;if(!*p||mpz_set_str(row[i],p,10)){*e=save;return-1;}*e=save;p=e;}return 0;}
int sda_falcon_bkz_solve(mpfr_t*a,mpfr_t eps,mpfr_prec_t pr,uint64_t seed,sda_falcon_bkz_result*r){(void)seed;memset(r,0,sizeof*r);r->selected_basis_row=-1;r->heuristic_bkz=1;r->exact_svp=0;if(!sda_falcon_bkz_available(r->version,sizeof r->version))return-10;char dir[128],in[160],out[160],err[160];snprintf(dir,sizeof dir,"build/falcon-bkz-temp/%ld",(long)getpid());mkdir("build",0777);mkdir("build/falcon-bkz-temp",0777);mkdir(dir,0777);snprintf(in,sizeof in,"%s/input.basis",dir);snprintf(out,sizeof out,"%s/output.basis",dir);snprintf(err,sizeof err,"%s/stderr.log",dir);FILE*f=fopen(in,"w");mpz_t D,A[19];mpz_init(D);for(int i=0;i<19;i++)mpz_init(A[i]);if(!f||sda_falcon_basis_write(f,a,eps,pr,D,A)){if(f)fclose(f);return-11;}fclose(f);snprintf(r->command,sizeof r->command,"fplll -a bkz -b 20 -bkzmaxloops 2 -f mpfr -p %lu %s",(unsigned long)pr,in);pid_t pid=fork();if(pid==0){int fo=open(out,O_CREAT|O_TRUNC|O_WRONLY,0600),fe=open(err,O_CREAT|O_TRUNC|O_WRONLY,0600);dup2(fo,1);dup2(fe,2);execlp("fplll","fplll","-a","bkz","-b","20","-bkzmaxloops","2","-f","mpfr","-p","256",in,(char*)0);_exit(127);}int st;waitpid(pid,&st,0);if(!WIFEXITED(st)||WEXITSTATUS(st)){r->solver_status=WIFEXITED(st)?WEXITSTATUS(st):-1;return-12;}f=fopen(out,"r");mpz_t row[20];for(int i=0;i<20;i++)mpz_init(row[i]);int rc=-20,row_index=0;char line[65536];while(f&&fgets(line,sizeof line,f)){if(parse_line(line,row))continue;sda_falcon_bkz_result c={0};int rr=sda_falcon_recover((const mpz_t*)row,D,(const mpz_t*)A,&c);if(!rr){r->recoverable_row_count++;sda_u128 sum=0;int zero=0,hole=0;for(int i=0;i<19;i++){sum+=c.p[i];if(!c.p[i])zero=1;else if(zero)hole=1;}if(c.q>0&&c.q<((sda_u128)1<<72)&&sum==c.q&&!hole){int v=r->valid_candidate_count;if(v<20){r->row_q[v]=c.q;r->row_index[v]=row_index;for(int i=0;i<19;i++)r->row_p[v][i]=c.p[i];r->valid_candidate_count++;}r->structurally_valid_row_count++;if(r->selected_basis_row<0){for(int i=0;i<19;i++)r->p[i]=c.p[i];r->q=c.q;r->selected_basis_row=row_index;rc=0;}}}row_index++;}if(f)fclose(f);for(int i=0;i<20;i++)mpz_clear(row[i]);for(int i=0;i<19;i++)mpz_clear(A[i]);mpz_clear(D);unlink(in);unlink(out);unlink(err);rmdir(dir);return rc;}
