#include <stdio.h>
#include "sda_random_driver.h"
#include "sda_epsilon.h"
#include "sda_falcon_bkz.h"
#include "sda_generation.h"
#include "sda_metrics.h"
#include <errno.h>
#include <string.h>
#include <sys/stat.h>

static void print_u128(FILE *f, sda_u128 x) { char b[64]; sda_print_u128(x,b,sizeof b); fputs(b,f); }
static void print_c_u128(FILE *f,sda_u128 x){fprintf(f,"(((sda_u128)%lluULL<<64)|(sda_u128)%lluULL)",(unsigned long long)(x>>64),(unsigned long long)x);}
static int make_dir(const char *p) { return mkdir(p,0777)==0 || errno==EEXIST ? 0 : -1; }
static void write_failure(const sda_config*c,mpfr_t lo,mpfr_t hi,uint64_t master,uint64_t seed,unsigned trials,const char*why,FILE*log){char dir[160],path[220];snprintf(dir,sizeof dir,"offline/generated/%s",c->parameter_set);if(make_dir("offline/generated")||make_dir(dir))return;snprintf(path,sizeof path,"%s/selected_report.txt",dir);FILE*f=fopen(path,"w");if(!f)return;fprintf(f,"parameter_set=%s\nepsilon_lower=",c->parameter_set);mpfr_out_str(f,10,0,lo,MPFR_RNDN);fprintf(f,"\nepsilon_upper=");mpfr_out_str(f,10,0,hi,MPFR_RNDN);fprintf(f,"\nmaster_seed=%llu\nparameter_seed=%llu\ntrials_completed=%u\ngeneration_status=not_found\nmain_failure_reason=%s\nnormalization_applied=false\ntrial_log:\n",(unsigned long long)master,(unsigned long long)seed,trials,why);rewind(log);int ch;while((ch=fgetc(log))!=EOF)fputc(ch,f);fclose(f);}
static const char *reason(const sda_generation_result *r, int rc) {
    if (rc != -8) return "solver_failure";
    if (!r->q) return "q_invalid";
    if (!r->raw_svp_pmf_valid) return "sum_mismatch";
    if (!r->baseline_dominance_certified) return "SD_or_RD_failure";
    return "candidate_invalid";
}
static int write_candidate(const sda_config *c,const sda_generation_result *r,
                           mpfr_t lo,mpfr_t hi,uint64_t master,uint64_t seed,
                           unsigned trial,FILE *log) {
    char dir[160],path[220]; snprintf(dir,sizeof dir,"offline/generated/%s",c->parameter_set);
    if(make_dir("offline/generated")||make_dir(dir))return -1;
    snprintf(path,sizeof path,"%s/selected_report.txt",dir); FILE*f=fopen(path,"w");if(!f)return -1;
    fprintf(f,"parameter_set=%s\nk=%d\nn=%zu\nepsilon_lower=",c->parameter_set,c->precision_k,r->n);mpfr_out_str(f,10,0,lo,MPFR_RNDN);fprintf(f,"\nepsilon_upper=");mpfr_out_str(f,10,0,hi,MPFR_RNDN);fprintf(f,"\nselected_epsilon=");mpfr_out_str(f,10,0,r->epsilon,MPFR_RNDN);
    fprintf(f,"\nmaster_seed=%llu\nparameter_seed=%llu\naccepted_trial=%u\nsolver=%s\nsolver_version=builtin-C17\nsolver_exact=%s\nMPFR_precision=%lu\nq=",(unsigned long long)master,(unsigned long long)seed,trial,r->solver,r->exact_linf_svp?"true":"false",(unsigned long)c->mpfr_precision);print_u128(f,r->q);
    fprintf(f,"\np=");for(size_t i=0;i<r->n;i++){if(i)fputc(' ',f);print_u128(f,r->p[i]);}fprintf(f,"\ncumulative=");for(size_t i=0;i<r->n;i++){if(i)fputc(' ',f);print_u128(f,r->c[i]);}
    fprintf(f,"\nmax_pointwise_error=");mpfr_out_str(f,10,0,r->max_abs_error,MPFR_RNDN);fprintf(f,"\nSD=");mpfr_out_str(f,10,0,r->sd_infinite,MPFR_RNDN);fprintf(f,"\nRD=");mpfr_out_str(f,10,0,r->renyi,MPFR_RNDN);fprintf(f,"\nRenyi_order=%ld\nsum_p_equals_q=true\nq_below_2k=true\nnormalization_applied=false\ngeneration_status=accepted\ntrial_log:\n",c->renyi_order);rewind(log);int ch;while((ch=fgetc(log))!=EOF)fputc(ch,f);fclose(f);
    snprintf(path,sizeof path,"%s/selected_table.txt",dir);f=fopen(path,"w");if(!f)return -1;fprintf(f,"q=");print_u128(f,r->q);fprintf(f,"\np=");for(size_t i=0;i<r->n;i++){if(i)fputc(' ',f);print_u128(f,r->p[i]);}fputc('\n',f);fclose(f);
    snprintf(path,sizeof path,"%s/selected_table.h",dir);f=fopen(path,"w");if(!f)return -1;fprintf(f,"/* Candidate only; not promoted online. */\n#include \"sda_u128.h\"\nstatic const sda_u128 selected_q=");print_c_u128(f,r->q);fprintf(f,";\nstatic const sda_u128 selected_p[]={");for(size_t i=0;i<r->n;i++){if(i)fputc(',',f);print_c_u128(f,r->p[i]);}fprintf(f,"};\nstatic const sda_u128 selected_cumulative[]={");for(size_t i=0;i<r->n;i++){if(i)fputc(',',f);print_c_u128(f,r->c[i]);}fprintf(f,"};\n");fclose(f);return 0;
}
int sda_random_generate_config(const char *path,uint64_t master,unsigned max_trials,const char *diagnostic_path){
    sda_config c;if(sda_config_load(path,&c))return 1;size_t n=(size_t)(c.support_max-c.support_min+1);uint64_t seed=sda_parameter_seed(master,c.parameter_set);sda_epsilon_rng rng;sda_epsilon_rng_init(&rng,seed);mpfr_t lo,hi,eps;mpfr_inits2(c.mpfr_precision,lo,hi,eps,(mpfr_ptr)0);sda_epsilon_bounds(c.precision_k,n,lo,hi);FILE*log=tmpfile();if(!log)return 1;
    if(!strcmp(c.scheme,"Falcon")){char v[128];if(!sda_falcon_bkz_available(v,sizeof v)){fprintf(stderr,"falcon: backend unavailable: fplll not found\n");fclose(log);mpfr_clears(lo,hi,eps,(mpfr_ptr)0);return 2;}FILE*diag=diagnostic_path?fopen(diagnostic_path,"w"):0;if(diag)fprintf(diag,"parameter_set,trial_index,epsilon,solver_return_code,q,sum_p,accept,reject_flags\n");unsigned completed=0,solverfail=0,sumfail=0,qfail=0,holefail=0;for(unsigned t=1;t<=max_trials;t++){sda_epsilon_random(&rng,lo,hi,eps);mpfr_t a[32],tail,gs;for(size_t i=0;i<n;i++)mpfr_init2(a[i],c.mpfr_precision);mpfr_inits2(c.mpfr_precision,tail,gs,(mpfr_ptr)0);sda_generate_distribution(&c,a,n,tail,gs);sda_falcon_bkz_result br;int rc=sda_falcon_bkz_solve(a,eps,c.mpfr_precision,seed+t,&br);completed++;sda_u128 sum=0;int hole=0,zero=0;for(size_t i=0;i<n;i++){sum+=br.p[i];if(!br.p[i])zero=1;else if(zero)hole=1;}unsigned flags=0;if(rc){flags|=SDA_REJECT_SOLVER;solverfail++;}if(!br.q||br.q>=((sda_u128)1<<72)){flags|=SDA_REJECT_Q_LARGE;qfail++;}if(sum!=br.q){flags|=SDA_REJECT_SUM;sumfail++;}if(hole){flags|=SDA_REJECT_ZERO_HOLE;holefail++;}if(!flags){sda_metrics fm;sda_metrics_init(&fm,c.mpfr_precision);sda_compute_metrics(a,n,br.p,br.q,509,&fm);mpfr_t plim,rdb;mpfr_inits2(c.mpfr_precision,plim,rdb,(mpfr_ptr)0);mpfr_set_ui_2exp(plim,1,-72,MPFR_RNDN);mpfr_set_ui_2exp(rdb,1,-78,MPFR_RNDN);mpfr_add_ui(rdb,rdb,1,MPFR_RNDN);if(mpfr_cmp(fm.max_absolute_error,plim)>0)flags|=SDA_REJECT_POINTWISE;if(mpfr_cmp(fm.renyi,rdb)>0)flags|=SDA_REJECT_RD;sda_metrics_clear(&fm);mpfr_clears(plim,rdb,(mpfr_ptr)0);}if(diag){fprintf(diag,"falcon,%u,",t);mpfr_out_str(diag,10,18,eps,MPFR_RNDN);fprintf(diag,",%d,",rc);print_u128(diag,br.q);fputc(44,diag);print_u128(diag,sum);fprintf(diag,",false,0x%x\n",flags);}for(size_t i=0;i<n;i++)mpfr_clear(a[i]);mpfr_clears(tail,gs,(mpfr_ptr)0);}if(diag)fclose(diag);fprintf(stderr,"falcon completed_trials=%u solver_failures=%u q_invalid=%u sum_mismatch=%u internal_zero=%u accepted_count=0 fplll_version=%s bkz_block_size=20\n",completed,solverfail,qfail,sumfail,holefail,v);fclose(log);mpfr_clears(lo,hi,eps,(mpfr_ptr)0);return 2;}
    FILE*diag=diagnostic_path?fopen(diagnostic_path,"w"):0;unsigned counts[11]={0},success=0,accepted=0;
    if(diag)fprintf(diag,"parameter_set,trial_index,epsilon,solver_return_code,solver_completed,q,q_bit_length,min_p,sum_p,sum_p_minus_q,terminal_cumulative,max_pointwise_error,pointwise_limit,SD,SD_baseline,RD,RD_baseline,support_valid,internal_zero_hole,accept,reject_flags\n");
    for(unsigned t=1;t<=max_trials;t++){sda_epsilon_random(&rng,lo,hi,eps);sda_candidate_diagnostic d;sda_candidate_diagnostic_init(&d,c.mpfr_precision);int rc=sda_diagnose_frodo_epsilon(&c,eps,&d);if(d.solver_completed)success++;for(int b=0;b<11;b++)if(d.reject_flags&(1u<<b))counts[b]++;if(!rc)accepted++;
      if(diag){fprintf(diag,"%s,%u,",c.parameter_set,t);mpfr_out_str(diag,10,18,eps,MPFR_RNDN);fprintf(diag,",%d,%s,",d.solver_rc,d.solver_completed?"true":"false");print_u128(diag,d.q);fprintf(diag,",%d,",d.q_bits);sda_u128 min=d.n?d.p[0]:0;for(size_t i=1;i<d.n;i++)if(d.p[i]<min)min=d.p[i];print_u128(diag,min);fputc(',',diag);print_u128(diag,d.sum);fprintf(diag,",%lld,",(long long)(d.sum-d.q));print_u128(diag,d.terminal);if(d.q&&!(d.reject_flags&(SDA_REJECT_Q_LARGE|SDA_REJECT_SUM))){fputc(',',diag);mpfr_out_str(diag,10,18,d.max_pointwise,MPFR_RNDN);fputc(',',diag);mpfr_out_str(diag,10,18,d.pointwise_limit,MPFR_RNDN);fputc(',',diag);mpfr_out_str(diag,10,18,d.sd,MPFR_RNDN);fputc(',',diag);mpfr_out_str(diag,10,18,d.sd_baseline,MPFR_RNDN);fputc(',',diag);mpfr_out_str(diag,10,18,d.rd,MPFR_RNDN);fputc(',',diag);mpfr_out_str(diag,10,18,d.rd_baseline,MPFR_RNDN);}else fprintf(diag,",unavailable,unavailable,unavailable,unavailable,unavailable,unavailable");fprintf(diag,",%s,%s,%s,0x%x\n",(d.reject_flags&SDA_REJECT_SUPPORT)?"false":"true",(d.reject_flags&SDA_REJECT_ZERO_HOLE)?"true":"false",rc?"false":"true",d.reject_flags);}
      fprintf(log,"%s,%u,%llu,",c.parameter_set,t,(unsigned long long)seed);mpfr_out_str(log,10,18,eps,MPFR_RNDN);fprintf(log,",%d,%s,0x%x\n",d.solver_rc,rc?"reject":"accept",d.reject_flags);sda_candidate_diagnostic_clear(&d);if(!rc){sda_generation_result r;sda_generation_result_init(&r,c.mpfr_precision);sda_generate_for_epsilon(&c,eps,&r);int w=write_candidate(&c,&r,lo,hi,master,seed,t,log);sda_generation_result_clear(&r);if(diag)fclose(diag);fclose(log);mpfr_clears(lo,hi,eps,(mpfr_ptr)0);return w?1:0;}}
    if(diag)fclose(diag);fprintf(stderr,"completed_trials=%u solver_success=%u solver_failures=%u q_zero_count=%u q_too_large_count=%u negative_mass_count=%u sum_mismatch_count=%u cumulative_mismatch_count=%u support_failure_count=%u internal_zero_count=%u pointwise_failure_count=%u sd_failure_count=%u rd_failure_count=%u accepted_count=%u\n",max_trials,success,counts[0],counts[1],counts[2],counts[3],counts[4],counts[5],counts[6],counts[7],counts[8],counts[9],counts[10],accepted);
    write_failure(&c,lo,hi,master,seed,max_trials,"no_legal_solver_candidate",log);fprintf(stderr,"%s: generation_status=not_found after %u trials\n",c.parameter_set,max_trials);fclose(log);mpfr_clears(lo,hi,eps,(mpfr_ptr)0);return 2;
}
