#include <stdio.h>
#include <string.h>
#include <mpfr.h>
#include "sda_generation.h"
static void u(FILE*f,sda_u128 v){ char b[64]; sda_print_u128(v,b,sizeof b); fputs(b,f); }
static void uexpr(FILE*f,sda_u128 v){ fprintf(f,"(sda_u128)"); u(f,v); fprintf(f,"ULL"); }
static void arr(FILE*f,const char*n,const sda_u128*a,size_t m){ fprintf(f,"static const sda_u128 %s[]={",n); for(size_t i=0;i<m;i++){ if(i)fputc(',',f); uexpr(f,a[i]); } fprintf(f,"};\n"); }
static int one(const char*path,const char*name,FILE*h,FILE*entries){ sda_config c; if(sda_config_load(path,&c)) return 1; size_t n=(size_t)(c.support_max-c.support_min+1); mpfr_t a[32],tail,gs,ms,ma,l1; for(size_t i=0;i<n;i++) mpfr_init2(a[i],c.mpfr_precision); mpfr_inits2(c.mpfr_precision,tail,gs,ms,ma,l1,(mpfr_ptr)0); sda_generate_distribution(&c,a,n,tail,gs); sda_u128 q=((sda_u128)1)<<c.precision_k,p[32],cum[32]; sda_fixed_q_minmax(a,n,q,p,ms,ma,l1); sda_build_cumulative(p,n,cum,&q); char pn[64],cn[64]; snprintf(pn,sizeof pn,"cdt_%s_p",name); snprintf(cn,sizeof cn,"cdt_%s_c",name); arr(h,pn,p,n); arr(h,cn,cum,n); fprintf(entries,"{\"%s\",\"%s\",\"classical-cdt\",0,%d,%d,0,0,0,%zu,",!strcmp(c.scheme,"Falcon")?"Falcon":"Frodo",name,c.support_max,c.precision_k,n); uexpr(entries,q); fprintf(entries,",%s,%s,%zu,%zu},\n",pn,cn,2*n*sizeof(sda_u128),n*(size_t)c.precision_k); for(size_t i=0;i<n;i++) mpfr_clear(a[i]); mpfr_clears(tail,gs,ms,ma,l1,(mpfr_ptr)0); return 0; }
int main(int argc,char**argv){ (void)argc; (void)argv; FILE*h=fopen("generated/classical_cdt_generated_tables.h","w"); FILE*e=tmpfile(); if(!h||!e) return 1; fprintf(h,"#ifndef CLASSICAL_CDT_GENERATED_TABLES_H\n#define CLASSICAL_CDT_GENERATED_TABLES_H\n#include \"sda_table.h\"\n"); one("config/frodo640.conf","frodo640",h,e); one("config/frodo976.conf","frodo976",h,e); one("config/frodo1344.conf","frodo1344",h,e); fprintf(h,"static const sda_table classical_cdt_generated_tables[]={\n"); rewind(e); int ch; while((ch=fgetc(e))!=EOF) fputc(ch,h); fprintf(h,"};\nstatic const size_t classical_cdt_generated_tables_count=3;\n#endif\n"); fclose(e); fclose(h); puts("generated classical CDT tables"); return 0; }
