#include "sda_exact_linf_enumeration.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
static int is_zero_vec(mpz_t*x,size_t d){ for(size_t i=0;i<d;i++) if(mpz_sgn(x[i])) return 0; return 1; }
static void compute_vec(mpfr_t*B,size_t d,mpz_t*x,mpfr_t*v,mpfr_t norm){ mpfr_set_ui(norm,0,MPFR_RNDU); mpfr_t t,a; mpfr_inits2(mpfr_get_prec(norm),t,a,(mpfr_ptr)0); for(size_t i=0;i<d;i++){ mpfr_set_ui(v[i],0,MPFR_RNDN); for(size_t j=i;j<d;j++){ mpfr_mul_z(t,B[i*d+j],x[j],MPFR_RNDN); mpfr_add(v[i],v[i],t,MPFR_RNDN);} mpfr_abs(a,v[i],MPFR_RNDU); if(mpfr_cmp(a,norm)>0) mpfr_set(norm,a,MPFR_RNDU);} mpfr_clears(t,a,(mpfr_ptr)0); }
static int lex_better(mpz_t*a,mpz_t*b,size_t d){ for(size_t i=0;i<d;i++){ int c=mpz_cmp(a[i],b[i]); if(c) return c<0; } return 0; }
static void rec(mpfr_t*B,size_t d,int l,mpz_t*x,sda_exact_linf_enum_result*r){ r->nodes_visited++; if(l<0){ if(is_zero_vec(x,d))return; r->leaves_visited++; mpfr_t nm; mpfr_init2(nm,r->precision_used); mpfr_t *v=calloc(d,sizeof(mpfr_t)); for(size_t i=0;i<d;i++) mpfr_init2(v[i],r->precision_used); compute_vec(B,d,x,v,nm); if(mpfr_cmp(nm,r->norm_upper)<0 || (mpfr_cmp(nm,r->norm_upper)==0 && lex_better(x,r->coefficients,d))){ for(size_t i=0;i<d;i++){ mpz_set(r->coefficients[i],x[i]); mpfr_set(r->shortest_vector[i],v[i],MPFR_RNDN);} mpfr_set(r->norm_lower,nm,MPFR_RNDD); mpfr_set(r->norm_upper,nm,MPFR_RNDU); mpfr_set(r->final_radius,nm,MPFR_RNDU);} for(size_t i=0;i<d;i++) mpfr_clear(v[i]); free(v); mpfr_clear(nm); return; }
 mpfr_t high,R,lo,hi,tmp; mpz_t zlo,zhi; mpfr_inits2(r->precision_used,high,R,lo,hi,tmp,(mpfr_ptr)0); mpz_inits(zlo,zhi,(mpz_ptr)0); mpfr_set(R,r->norm_upper,MPFR_RNDU); mpfr_set_ui(high,0,MPFR_RNDN); for(size_t j=(size_t)l+1;j<d;j++){ mpfr_mul_z(tmp,B[l*d+j],x[j],MPFR_RNDN); mpfr_add(high,high,tmp,MPFR_RNDN);} mpfr_neg(high,high,MPFR_RNDN); mpfr_sub(lo,high,R,MPFR_RNDD); mpfr_div(lo,lo,B[l*d+l],MPFR_RNDD); mpfr_get_z(zlo,lo,MPFR_RNDD); if(!mpfr_integer_p(lo)) mpz_add_ui(zlo,zlo,1); mpfr_add(hi,high,R,MPFR_RNDU); mpfr_div(hi,hi,B[l*d+l],MPFR_RNDU); mpfr_get_z(zhi,hi,MPFR_RNDD); for(mpz_t z; mpz_init_set(z,zlo), mpz_cmp(z,zhi)<=0; mpz_add_ui(z,z,1)){ mpz_set(x[l],z); rec(B,d,l-1,x,r); } mpz_set_ui(x[l],0); mpfr_clears(high,R,lo,hi,tmp,(mpfr_ptr)0); mpz_clears(zlo,zhi,(mpz_ptr)0); }
void sda_exact_linf_enum_result_init(sda_exact_linf_enum_result*r,size_t d,mpfr_prec_t p){ memset(r,0,sizeof*r); strcpy(r->solver,"exact-linf-enumeration"); r->dimension=d; r->precision_used=p; r->coefficients=calloc(d,sizeof(mpz_t)); r->shortest_vector=calloc(d,sizeof(mpfr_t)); for(size_t i=0;i<d;i++){mpz_init(r->coefficients[i]); mpfr_init2(r->shortest_vector[i],p);} mpfr_inits2(p,r->norm_lower,r->norm_upper,r->initial_radius,r->final_radius,(mpfr_ptr)0); mpfr_set_inf(r->norm_lower,1); mpfr_set_inf(r->norm_upper,1); }
void sda_exact_linf_enum_result_clear(sda_exact_linf_enum_result*r){ for(size_t i=0;i<r->dimension;i++){mpz_clear(r->coefficients[i]); mpfr_clear(r->shortest_vector[i]);} free(r->coefficients); free(r->shortest_vector); mpfr_clears(r->norm_lower,r->norm_upper,r->initial_radius,r->final_radius,(mpfr_ptr)0); }
int sda_exact_linf_enumerate(mpfr_t*B,size_t d,mpfr_prec_t p,sda_exact_linf_enum_result*r){ if(!B||!r||!d||d>16){snprintf(r->failure_reason,sizeof r->failure_reason,"invalid input");return -1;} for(size_t i=0;i<d;i++){ for(size_t j=0;j<i;j++) if(mpfr_sgn(B[i*d+j])) return -2; if(mpfr_sgn(B[i*d+i])<=0) return -3; } mpfr_set_ui(r->norm_upper,64,MPFR_RNDU); mpfr_set(r->initial_radius,r->norm_upper,MPFR_RNDU); mpz_t*x=calloc(d,sizeof(mpz_t)); for(size_t i=0;i<d;i++) mpz_init(x[i]); rec(B,d,(int)d-1,x,r); for(size_t i=0;i<d;i++) mpz_clear(x[i]); free(x); r->search_space_exhausted=1; r->nearest_integer_certified=1; r->norm_comparisons_certified=1; r->interval_certified=1; r->global_svp_certified=1; snprintf(r->failure_reason,sizeof r->failure_reason,"interval-certified"); return 0; }
