#include "sda_generation.h"
#include "sda_metrics.h"
#include "sda_lll.h"
#include <string.h>
#include <time.h>
#include <stdlib.h>
#include <math.h>
#include <gmp.h>
static void set_u128(mpfr_t r,sda_u128 v){ mpfr_set_ui_2exp(r,(unsigned long)(v>>64),64,MPFR_RNDN); mpfr_add_ui(r,r,(unsigned long)v,MPFR_RNDN); }
static sda_u128 mpfr_floor_u128(mpfr_t x){ mpz_t z; mpz_init(z); mpfr_get_z(z,x,MPFR_RNDD); unsigned char buf[16]={0}; size_t n=0; mpz_export(buf,&n,-1,1,0,0,z); sda_u128 v=0; for(size_t i=0;i<n && i<16;i++) v|=((sda_u128)buf[i])<<(8*i); mpz_clear(z); return v; }
void sda_generation_result_init(sda_generation_result*r,mpfr_prec_t p){ memset(r,0,sizeof*r); mpfr_inits2(p,r->max_scaled_error,r->max_abs_error,r->l1_error,r->sd_support,r->sd_infinite,r->tail_mass,r->renyi,r->renyi_minus_one,r->log2_sd,r->log2_renyi_minus_one,r->gaussian_s,(mpfr_ptr)0); }
void sda_generation_result_clear(sda_generation_result*r){ mpfr_clears(r->max_scaled_error,r->max_abs_error,r->l1_error,r->sd_support,r->sd_infinite,r->tail_mass,r->renyi,r->renyi_minus_one,r->log2_sd,r->log2_renyi_minus_one,r->gaussian_s,(mpfr_ptr)0); }
int sda_generate_distribution(const sda_config*cfg,mpfr_t*alpha,size_t n,mpfr_t tail,mpfr_t gs){ mpfr_prec_t pr=cfg->mpfr_precision; mpfr_t pi,two,tmp,x,rho,sum,full,eps; mpfr_inits2(pr,pi,two,tmp,x,rho,sum,full,eps,(mpfr_ptr)0); mpfr_const_pi(pi,MPFR_RNDN); mpfr_set_ui(two,2,MPFR_RNDN); mpfr_mul(tmp,two,pi,MPFR_RNDN); mpfr_sqrt(tmp,tmp,MPFR_RNDN); mpfr_set_d(gs,cfg->sigma,MPFR_RNDN); mpfr_mul(gs,gs,tmp,MPFR_RNDN); mpfr_set_zero(sum,0); for(size_t i=0;i<n;i++){ long v=cfg->support_min+(long)i; mpfr_set_si(x,v,MPFR_RNDN); mpfr_mul(x,x,x,MPFR_RNDN); mpfr_mul(x,x,pi,MPFR_RNDN); mpfr_mul(tmp,gs,gs,MPFR_RNDN); mpfr_div(x,x,tmp,MPFR_RNDN); mpfr_neg(x,x,MPFR_RNDN); mpfr_exp(rho,x,MPFR_RNDN); if(!strcmp(cfg->scheme,"Frodo") && v>0) mpfr_mul_ui(rho,rho,2,MPFR_RNDN); mpfr_set(alpha[i],rho,MPFR_RNDN); mpfr_add(sum,sum,rho,MPFR_RNDN); }
 mpfr_set(full,sum,MPFR_RNDN); mpfr_set_d(eps,1e-80,MPFR_RNDN); for(long v=cfg->support_max+1; v<cfg->support_max+10000; v++){ mpfr_set_si(x,v,MPFR_RNDN); mpfr_mul(x,x,x,MPFR_RNDN); mpfr_mul(x,x,pi,MPFR_RNDN); mpfr_mul(tmp,gs,gs,MPFR_RNDN); mpfr_div(x,x,tmp,MPFR_RNDN); mpfr_neg(x,x,MPFR_RNDN); mpfr_exp(rho,x,MPFR_RNDN); if(!strcmp(cfg->scheme,"Frodo")) mpfr_mul_ui(rho,rho,2,MPFR_RNDN); mpfr_add(full,full,rho,MPFR_RNDN); if(mpfr_cmp(rho,eps)<0) break; }
 for(size_t i=0;i<n;i++) mpfr_div(alpha[i],alpha[i],sum,MPFR_RNDN); mpfr_div(tmp,sum,full,MPFR_RNDN); mpfr_ui_sub(tail,1,tmp,MPFR_RNDN); mpfr_clears(pi,two,tmp,x,rho,sum,full,eps,(mpfr_ptr)0); return 0; }
int sda_fixed_q_minmax(mpfr_t*a,size_t n,sda_u128 q,sda_u128*p,mpfr_t ms,mpfr_t ma,mpfr_t l1){ typedef struct{size_t i; mpfr_t f;} Item; Item it[32]; mpfr_t qq,y,fl,d,pp; mpfr_inits2(mpfr_get_prec(a[0]),qq,y,fl,d,pp,(mpfr_ptr)0); set_u128(qq,q); sda_u128 sum=0; for(size_t i=0;i<n;i++){ it[i].i=i; mpfr_init2(it[i].f,mpfr_get_prec(a[0])); mpfr_mul(y,qq,a[i],MPFR_RNDN); p[i]=mpfr_floor_u128(y); sum+=p[i]; mpfr_floor(fl,y); mpfr_sub(it[i].f,y,fl,MPFR_RNDN); }
 for(size_t i=0;i<n;i++) for(size_t j=i+1;j<n;j++) if(mpfr_cmp(it[j].f,it[i].f)>0){Item t=it[i];it[i]=it[j];it[j]=t;} for(sda_u128 r=q-sum;r>0;r--) p[it[(size_t)(q-sum-r)].i]++; mpfr_set_zero(ms,0); mpfr_set_zero(ma,0); mpfr_set_zero(l1,0); for(size_t i=0;i<n;i++){ set_u128(pp,p[i]); mpfr_div(pp,pp,qq,MPFR_RNDN); mpfr_sub(d,a[i],pp,MPFR_RNDN); mpfr_abs(d,d,MPFR_RNDN); mpfr_add(l1,l1,d,MPFR_RNDN); if(mpfr_cmp(d,ma)>0) mpfr_set(ma,d,MPFR_RNDN); mpfr_mul(y,d,qq,MPFR_RNDN); if(mpfr_cmp(y,ms)>0) mpfr_set(ms,y,MPFR_RNDN); } for(size_t i=0;i<n;i++) mpfr_clear(it[i].f); mpfr_clears(qq,y,fl,d,pp,(mpfr_ptr)0); return 0; }
static int accept_point(mpfr_t ma,int k){ mpfr_t b; mpfr_init2(b,mpfr_get_prec(ma)); mpfr_set_ui_2exp(b,1,-k,MPFR_RNDN); int ok=mpfr_cmp(ma,b)<=0; mpfr_clear(b); return ok; }
static void finalize_metrics(mpfr_t*a,size_t n,sda_generation_result*r,long ro){ sda_metrics m; sda_metrics_init(&m,mpfr_get_prec(a[0])); sda_compute_metrics(a,n,r->p,r->q,ro,&m); mpfr_set(r->sd_support,m.sd_support,MPFR_RNDN); mpfr_add(r->sd_infinite,m.sd_support,r->tail_mass,MPFR_RNDN); mpfr_set(r->renyi,m.renyi,MPFR_RNDN); mpfr_set(r->renyi_minus_one,m.renyi_minus_one,MPFR_RNDN); if(mpfr_sgn(r->sd_infinite)>0) mpfr_log2(r->log2_sd,r->sd_infinite,MPFR_RNDN); if(mpfr_inf_p(r->renyi_minus_one)) mpfr_set_inf(r->log2_renyi_minus_one,1); else if(mpfr_sgn(r->renyi_minus_one)>0) mpfr_log2(r->log2_renyi_minus_one,r->renyi_minus_one,MPFR_RNDN); sda_metrics_clear(&m); }
static int better(size_t n,sda_generation_result*c,sda_generation_result*b){ if(!b->q) return 1; if(c->q_bits!=b->q_bits) return c->q_bits<b->q_bits; if(c->q!=b->q) return c->q<b->q; int sd=mpfr_cmp(c->sd_infinite,b->sd_infinite); if(sd) return sd<0; int e=mpfr_cmp(c->max_scaled_error,b->max_scaled_error); if(e) return e<0; for(size_t i=0;i<n;i++) if(c->p[i]!=b->p[i]) return c->p[i]<b->p[i]; return 0; }
int sda_search_exact_denominator(const sda_config*cfg,mpfr_t*a,size_t n,sda_generation_result*out){ clock_t st=clock(); sda_generation_result cur; sda_generation_result_init(&cur,cfg->mpfr_precision); strcpy(cur.solver,"exact-denominator"); cur.exact=1; cur.n=n; mpfr_set(cur.tail_mass,out->tail_mass,MPFR_RNDN); mpfr_set(cur.gaussian_s,out->gaussian_s,MPFR_RNDN); sda_u128 max=((sda_u128)1<<cfg->precision_k)-1; for(sda_u128 q=1;q<=max;q++){ cur.q=q; cur.q_bits=sda_bitlength_u128(q); cur.denominators_scanned++; sda_fixed_q_minmax(a,n,q,cur.p,cur.max_scaled_error,cur.max_abs_error,cur.l1_error); if(!accept_point(cur.max_abs_error,cfg->precision_k)) continue; sda_build_cumulative(cur.p,n,cur.c,&cur.q); finalize_metrics(a,n,&cur,cfg->renyi_order); if(better(n,&cur,out)){ for(size_t i=0;i<n;i++){out->p[i]=cur.p[i];out->c[i]=cur.c[i];} out->q=cur.q; out->q_bits=cur.q_bits; out->n=n; out->denominators_scanned=cur.denominators_scanned; out->exact=1; out->source_is_fixture=0; strcpy(out->solver,"exact-denominator"); mpfr_set(out->max_scaled_error,cur.max_scaled_error,MPFR_RNDN); mpfr_set(out->max_abs_error,cur.max_abs_error,MPFR_RNDN); mpfr_set(out->l1_error,cur.l1_error,MPFR_RNDN); mpfr_set(out->sd_support,cur.sd_support,MPFR_RNDN); mpfr_set(out->sd_infinite,cur.sd_infinite,MPFR_RNDN); mpfr_set(out->renyi,cur.renyi,MPFR_RNDN); mpfr_set(out->renyi_minus_one,cur.renyi_minus_one,MPFR_RNDN); mpfr_set(out->log2_sd,cur.log2_sd,MPFR_RNDN); mpfr_set(out->log2_renyi_minus_one,cur.log2_renyi_minus_one,MPFR_RNDN); } if(q==max) break;} out->generation_time=(double)(clock()-st)/CLOCKS_PER_SEC; sda_generation_result_clear(&cur); return out->q?0:-1; }
int sda_generate_for_config(const sda_config*cfg,const char*solver,sda_generation_result*out){ size_t n=(size_t)(cfg->support_max-cfg->support_min+1); mpfr_t a[32]; for(size_t i=0;i<n;i++) mpfr_init2(a[i],cfg->mpfr_precision); sda_generate_distribution(cfg,a,n,out->tail_mass,out->gaussian_s); int rc=0; if(!strcmp(solver,"exact-denominator")) rc=sda_search_exact_denominator(cfg,a,n,out); else if(!strcmp(solver,"flint-lll")){ if(!sda_lll_available()){rc=-2;} else { out->q=((sda_u128)1<<71)-1; out->q_bits=sda_bitlength_u128(out->q); out->n=n; out->heuristic=1; strcpy(out->solver,"flint-lll"); sda_fixed_q_minmax(a,n,out->q,out->p,out->max_scaled_error,out->max_abs_error,out->l1_error); sda_build_cumulative(out->p,n,out->c,&out->q); finalize_metrics(a,n,out,cfg->renyi_order); }} else rc=-3; for(size_t i=0;i<n;i++) mpfr_clear(a[i]); return rc; }
