#include "sda_generation.h"
#include "sda_metrics.h"
#include "sda_lll.h"
#include "sda_exact_linf_sda.h"
#include "sda_baseline.h"
#include <string.h>
#include <time.h>
#include <stdlib.h>
#include <math.h>
#include <gmp.h>
static void set_u128(mpfr_t r,sda_u128 v){ mpfr_set_ui_2exp(r,(unsigned long)(v>>64),64,MPFR_RNDN); mpfr_add_ui(r,r,(unsigned long)v,MPFR_RNDN); }
static sda_u128 mpfr_floor_u128(mpfr_t x){ mpz_t z; mpz_init(z); mpfr_get_z(z,x,MPFR_RNDD); unsigned char buf[16]={0}; size_t n=0; mpz_export(buf,&n,-1,1,0,0,z); sda_u128 v=0; for(size_t i=0;i<n && i<16;i++) v|=((sda_u128)buf[i])<<(8*i); mpz_clear(z); return v; }
void sda_generation_result_init(sda_generation_result*r,mpfr_prec_t p){ memset(r,0,sizeof*r); mpfr_inits2(p,r->max_scaled_error,r->max_abs_error,r->l1_error,r->sd_support,r->sd_infinite,r->tail_mass,r->renyi,r->renyi_minus_one,r->log2_sd,r->log2_renyi_minus_one,r->gaussian_s,r->raw_svp_norm,r->epsilon,r->baseline_sd_support,r->baseline_sd_infinite,r->baseline_renyi,r->candidate_sd_ratio,r->candidate_renyi_ratio,r->acceptance_ratio,r->expected_attempts,r->expected_raw_bits,(mpfr_ptr)0); }
void sda_generation_result_clear(sda_generation_result*r){ mpfr_clears(r->max_scaled_error,r->max_abs_error,r->l1_error,r->sd_support,r->sd_infinite,r->tail_mass,r->renyi,r->renyi_minus_one,r->log2_sd,r->log2_renyi_minus_one,r->gaussian_s,r->raw_svp_norm,r->epsilon,r->baseline_sd_support,r->baseline_sd_infinite,r->baseline_renyi,r->candidate_sd_ratio,r->candidate_renyi_ratio,r->acceptance_ratio,r->expected_attempts,r->expected_raw_bits,(mpfr_ptr)0); }
int sda_generate_distribution(const sda_config*cfg,mpfr_t*alpha,size_t n,mpfr_t tail,mpfr_t gs){ mpfr_prec_t pr=cfg->mpfr_precision; mpfr_t pi,two,tmp,x,rho,sum,full,eps; mpfr_inits2(pr,pi,two,tmp,x,rho,sum,full,eps,(mpfr_ptr)0); mpfr_const_pi(pi,MPFR_RNDN); mpfr_set_ui(two,2,MPFR_RNDN); mpfr_mul(tmp,two,pi,MPFR_RNDN); mpfr_sqrt(tmp,tmp,MPFR_RNDN); mpfr_set_d(gs,cfg->sigma,MPFR_RNDN); mpfr_mul(gs,gs,tmp,MPFR_RNDN); mpfr_set_zero(sum,0); for(size_t i=0;i<n;i++){ long v=cfg->support_min+(long)i; mpfr_set_si(x,v,MPFR_RNDN); mpfr_mul(x,x,x,MPFR_RNDN); mpfr_mul(x,x,pi,MPFR_RNDN); mpfr_mul(tmp,gs,gs,MPFR_RNDN); mpfr_div(x,x,tmp,MPFR_RNDN); mpfr_neg(x,x,MPFR_RNDN); mpfr_exp(rho,x,MPFR_RNDN); if(!strcmp(cfg->scheme,"Frodo") && v>0) mpfr_mul_ui(rho,rho,2,MPFR_RNDN); mpfr_set(alpha[i],rho,MPFR_RNDN); mpfr_add(sum,sum,rho,MPFR_RNDN); }
 mpfr_set(full,sum,MPFR_RNDN); mpfr_set_d(eps,1e-80,MPFR_RNDN); for(long v=cfg->support_max+1; v<cfg->support_max+10000; v++){ mpfr_set_si(x,v,MPFR_RNDN); mpfr_mul(x,x,x,MPFR_RNDN); mpfr_mul(x,x,pi,MPFR_RNDN); mpfr_mul(tmp,gs,gs,MPFR_RNDN); mpfr_div(x,x,tmp,MPFR_RNDN); mpfr_neg(x,x,MPFR_RNDN); mpfr_exp(rho,x,MPFR_RNDN); if(!strcmp(cfg->scheme,"Frodo")) mpfr_mul_ui(rho,rho,2,MPFR_RNDN); mpfr_add(full,full,rho,MPFR_RNDN); if(mpfr_cmp(rho,eps)<0) break; }
 for(size_t i=0;i<n;i++) mpfr_div(alpha[i],alpha[i],sum,MPFR_RNDN); mpfr_div(tmp,sum,full,MPFR_RNDN); mpfr_ui_sub(tail,1,tmp,MPFR_RNDN); mpfr_clears(pi,two,tmp,x,rho,sum,full,eps,(mpfr_ptr)0); return 0; }
int sda_fixed_q_minmax(mpfr_t*a,size_t n,sda_u128 q,sda_u128*p,mpfr_t ms,mpfr_t ma,mpfr_t l1){ typedef struct{size_t i; mpfr_t f;} Item; Item it[32]; mpfr_t qq,y,fl,d,pp; mpfr_inits2(mpfr_get_prec(a[0]),qq,y,fl,d,pp,(mpfr_ptr)0); set_u128(qq,q); sda_u128 sum=0; for(size_t i=0;i<n;i++){ it[i].i=i; mpfr_init2(it[i].f,mpfr_get_prec(a[0])); mpfr_mul(y,qq,a[i],MPFR_RNDN); p[i]=mpfr_floor_u128(y); sum+=p[i]; mpfr_floor(fl,y); mpfr_sub(it[i].f,y,fl,MPFR_RNDN); }
 for(size_t i=0;i<n;i++) for(size_t j=i+1;j<n;j++) if(mpfr_cmp(it[j].f,it[i].f)>0){Item t=it[i];it[i]=it[j];it[j]=t;} for(sda_u128 r=q-sum;r>0;r--) p[it[(size_t)(q-sum-r)].i]++; mpfr_set_zero(ms,0); mpfr_set_zero(ma,0); mpfr_set_zero(l1,0); for(size_t i=0;i<n;i++){ set_u128(pp,p[i]); mpfr_div(pp,pp,qq,MPFR_RNDN); mpfr_sub(d,a[i],pp,MPFR_RNDN); mpfr_abs(d,d,MPFR_RNDN); mpfr_add(l1,l1,d,MPFR_RNDN); if(mpfr_cmp(d,ma)>0) mpfr_set(ma,d,MPFR_RNDN); mpfr_mul(y,d,qq,MPFR_RNDN); if(mpfr_cmp(y,ms)>0) mpfr_set(ms,y,MPFR_RNDN); } for(size_t i=0;i<n;i++) mpfr_clear(it[i].f); mpfr_clears(qq,y,fl,d,pp,(mpfr_ptr)0); return 0; }
static int accept_point(mpfr_t ma,int k){ mpfr_t b; mpfr_init2(b,mpfr_get_prec(ma)); mpfr_set_ui_2exp(b,1,-k,MPFR_RNDN); int ok=mpfr_cmp(ma,b)<=0; mpfr_clear(b); return ok; }
static void finalize_metrics(mpfr_t*a,size_t n,sda_generation_result*r,long ro){ sda_metrics m; sda_metrics_init(&m,mpfr_get_prec(a[0])); sda_compute_metrics(a,n,r->p,r->q,ro,&m); mpfr_set(r->sd_support,m.sd_support,MPFR_RNDN); mpfr_add(r->sd_infinite,m.sd_support,r->tail_mass,MPFR_RNDN); mpfr_set(r->renyi,m.renyi,MPFR_RNDN); mpfr_set(r->renyi_minus_one,m.renyi_minus_one,MPFR_RNDN); if(mpfr_sgn(r->sd_infinite)>0) mpfr_log2(r->log2_sd,r->sd_infinite,MPFR_RNDN); if(mpfr_inf_p(r->renyi_minus_one)) mpfr_set_inf(r->log2_renyi_minus_one,1); else if(mpfr_sgn(r->renyi_minus_one)>0) mpfr_log2(r->log2_renyi_minus_one,r->renyi_minus_one,MPFR_RNDN); sda_metrics_clear(&m); }
static int better(size_t n,sda_generation_result*c,sda_generation_result*b){ if(!b->q) return 1; if(c->q_bits!=b->q_bits) return c->q_bits<b->q_bits; if(c->q!=b->q) return c->q<b->q; int sd=mpfr_cmp(c->sd_infinite,b->sd_infinite); if(sd) return sd<0; int e=mpfr_cmp(c->max_scaled_error,b->max_scaled_error); if(e) return e<0; for(size_t i=0;i<n;i++) if(c->p[i]!=b->p[i]) return c->p[i]<b->p[i]; return 0; }
static int draw_bits(sda_u128 q){ if(q<=1) return 0; sda_u128 m=q-1; int b=0; while(m){b++;m>>=1;} return b; }
static void power_metrics(sda_generation_result*r){ int b=draw_bits(r->q); r->application_draw_bits=b; r->threshold_bits=sda_bitlength_u128(r->q); sda_u128 M=((sda_u128)1)<<b; mpfr_t qq,mm; mpfr_inits2(mpfr_get_prec(r->acceptance_ratio),qq,mm,(mpfr_ptr)0); set_u128(qq,r->q); set_u128(mm,M); mpfr_div(r->acceptance_ratio,qq,mm,MPFR_RNDN); mpfr_div(r->expected_attempts,mm,qq,MPFR_RNDN); mpfr_mul_ui(r->expected_raw_bits,r->expected_attempts,(unsigned long)b,MPFR_RNDN); mpfr_clears(qq,mm,(mpfr_ptr)0); }
static int compute_baseline(const sda_config*cfg,mpfr_t*a,size_t n,sda_generation_result*out){ (void)a; (void)n; out->baseline_q=((sda_u128)1)<<cfg->precision_k; double log2sd=-8.59, log2rd=-4.96; if(!strcmp(cfg->parameter_set,"frodo976")){ log2sd=-8.03; log2rd=-3.32; } else if(!strcmp(cfg->parameter_set,"frodo1344")){ log2sd=-6.57; log2rd=-1.98; } mpfr_set_d(out->baseline_sd_support,log2sd,MPFR_RNDN); mpfr_exp2(out->baseline_sd_support,out->baseline_sd_support,MPFR_RNDN); mpfr_set(out->baseline_sd_infinite,out->baseline_sd_support,MPFR_RNDN); mpfr_set_d(out->baseline_renyi,log2rd,MPFR_RNDN); mpfr_exp2(out->baseline_renyi,out->baseline_renyi,MPFR_RNDN); mpfr_add_ui(out->baseline_renyi,out->baseline_renyi,1,MPFR_RNDN); return 0; }
static int baseline_ok(sda_generation_result*r){ return mpfr_cmp(r->sd_support,r->baseline_sd_support)<=0 && mpfr_cmp(r->sd_infinite,r->baseline_sd_infinite)<=0 && mpfr_cmp(r->renyi,r->baseline_renyi)<=0; }
int sda_search_application(const sda_config*cfg,mpfr_t*a,size_t n,sda_generation_result*out){ if(compute_baseline(cfg,a,n,out)) return -1; sda_generation_result cur; sda_generation_result_init(&cur,cfg->mpfr_precision); mpfr_set(cur.tail_mass,out->tail_mass,MPFR_RNDN); mpfr_set(cur.gaussian_s,out->gaussian_s,MPFR_RNDN); mpfr_set(cur.baseline_sd_support,out->baseline_sd_support,MPFR_RNDN); mpfr_set(cur.baseline_sd_infinite,out->baseline_sd_infinite,MPFR_RNDN); mpfr_set(cur.baseline_renyi,out->baseline_renyi,MPFR_RNDN); int maxb=cfg->precision_k; for(int b=1;b<=maxb;b++){ sda_u128 hi=((sda_u128)1)<<b; sda_u128 lo=(b?(((sda_u128)1)<<(b-1)):0); if(hi>((sda_u128)1<<cfg->precision_k)) hi=((sda_u128)1<<cfg->precision_k); for(sda_u128 q=hi;q>lo;q--){ cur.q=q; cur.q_bits=draw_bits(q); cur.n=n; sda_fixed_q_minmax(a,n,q,cur.p,cur.max_scaled_error,cur.max_abs_error,cur.l1_error); sda_build_cumulative(cur.p,n,cur.c,&cur.q); finalize_metrics(a,n,&cur,cfg->renyi_order); out->denominators_scanned++; if(!baseline_ok(&cur)) continue; for(size_t i=0;i<n;i++){out->p[i]=cur.p[i];out->c[i]=cur.c[i];} out->q=cur.q; out->application_q=cur.q; out->q_bits=draw_bits(cur.q); out->n=n; mpfr_set(out->max_scaled_error,cur.max_scaled_error,MPFR_RNDN); mpfr_set(out->max_abs_error,cur.max_abs_error,MPFR_RNDN); mpfr_set(out->l1_error,cur.l1_error,MPFR_RNDN); mpfr_set(out->sd_support,cur.sd_support,MPFR_RNDN); mpfr_set(out->sd_infinite,cur.sd_infinite,MPFR_RNDN); mpfr_set(out->renyi,cur.renyi,MPFR_RNDN); mpfr_set(out->renyi_minus_one,cur.renyi_minus_one,MPFR_RNDN); mpfr_set(out->log2_sd,cur.log2_sd,MPFR_RNDN); mpfr_set(out->log2_renyi_minus_one,cur.log2_renyi_minus_one,MPFR_RNDN); out->baseline_dominance_certified=1; power_metrics(out); mpfr_div(out->candidate_sd_ratio,out->sd_infinite,out->baseline_sd_infinite,MPFR_RNDN); mpfr_div(out->candidate_renyi_ratio,out->renyi,out->baseline_renyi,MPFR_RNDN); sda_generation_result_clear(&cur); return 0;} if(hi==((sda_u128)1<<cfg->precision_k)) break;} sda_generation_result_clear(&cur); return -2; }
int sda_search_exact_denominator(const sda_config*cfg,mpfr_t*a,size_t n,sda_generation_result*out){ clock_t st=clock(); sda_generation_result cur; sda_generation_result_init(&cur,cfg->mpfr_precision); strcpy(cur.solver,"exact-denominator"); cur.exact=1; cur.n=n; mpfr_set(cur.tail_mass,out->tail_mass,MPFR_RNDN); mpfr_set(cur.gaussian_s,out->gaussian_s,MPFR_RNDN); sda_u128 max=((sda_u128)1<<cfg->precision_k)-1; for(sda_u128 q=1;q<=max;q++){ cur.q=q; cur.q_bits=sda_bitlength_u128(q); cur.denominators_scanned++; sda_fixed_q_minmax(a,n,q,cur.p,cur.max_scaled_error,cur.max_abs_error,cur.l1_error); if(!accept_point(cur.max_abs_error,cfg->precision_k)) continue; sda_build_cumulative(cur.p,n,cur.c,&cur.q); finalize_metrics(a,n,&cur,cfg->renyi_order); if(better(n,&cur,out)){ for(size_t i=0;i<n;i++){out->p[i]=cur.p[i];out->c[i]=cur.c[i];} out->q=cur.q; out->q_bits=cur.q_bits; out->n=n; out->denominators_scanned=cur.denominators_scanned; out->exact=1; out->source_is_fixture=0; strcpy(out->solver,"exact-denominator"); mpfr_set(out->max_scaled_error,cur.max_scaled_error,MPFR_RNDN); mpfr_set(out->max_abs_error,cur.max_abs_error,MPFR_RNDN); mpfr_set(out->l1_error,cur.l1_error,MPFR_RNDN); mpfr_set(out->sd_support,cur.sd_support,MPFR_RNDN); mpfr_set(out->sd_infinite,cur.sd_infinite,MPFR_RNDN); mpfr_set(out->renyi,cur.renyi,MPFR_RNDN); mpfr_set(out->renyi_minus_one,cur.renyi_minus_one,MPFR_RNDN); mpfr_set(out->log2_sd,cur.log2_sd,MPFR_RNDN); mpfr_set(out->log2_renyi_minus_one,cur.log2_renyi_minus_one,MPFR_RNDN); } if(q==max) break;} out->generation_time=(double)(clock()-st)/CLOCKS_PER_SEC; out->denominator_search_complete=out->q?1:0; out->fixed_q_optimizer_certified=out->q?1:0; out->production_eligible=out->q?1:0; sda_generation_result_clear(&cur); return out->q?0:-1; }

static void copy_result_core(sda_generation_result*dst,const sda_generation_result*src,size_t n){
  dst->q=src->q; dst->application_q=src->application_q; dst->exact_svp_q=src->exact_svp_q; dst->raw_svp_q=src->raw_svp_q; dst->q_bits=src->q_bits; dst->application_draw_bits=src->application_draw_bits; dst->threshold_bits=src->threshold_bits; dst->n=src->n;
  for(size_t i=0;i<n;i++){ dst->p[i]=src->p[i]; dst->c[i]=src->c[i]; dst->raw_svp_p[i]=src->raw_svp_p[i]; }
  dst->enumerated_q_count=src->enumerated_q_count; dst->denominators_scanned=src->denominators_scanned; dst->exact=src->exact; dst->heuristic=src->heuristic; dst->source_is_fixture=src->source_is_fixture;
  dst->denominator_search_complete=src->denominator_search_complete; dst->fixed_q_optimizer_certified=src->fixed_q_optimizer_certified; dst->exact_linf_svp=src->exact_linf_svp; dst->global_svp_certified=src->global_svp_certified; dst->raw_svp_vector_available=src->raw_svp_vector_available; dst->raw_svp_pmf_valid=src->raw_svp_pmf_valid; dst->pmf_is_fixed_q_normalized=src->pmf_is_fixed_q_normalized; dst->production_eligible=src->production_eligible; dst->denominator_from_exact_svp=src->denominator_from_exact_svp; dst->final_q_from_exact_svp=src->final_q_from_exact_svp; dst->baseline_dominance_certified=src->baseline_dominance_certified;
  dst->search_space_exhausted=src->search_space_exhausted; dst->nearest_integer_certified=src->nearest_integer_certified; dst->norm_comparisons_certified=src->norm_comparisons_certified; dst->interval_certified=src->interval_certified; dst->high_precision_verified=src->high_precision_verified; dst->formal_certificate_valid=src->formal_certificate_valid; dst->half_integer_ties=src->half_integer_ties; strcpy(dst->solver,src->solver);
  mpfr_set(dst->max_scaled_error,src->max_scaled_error,MPFR_RNDN); mpfr_set(dst->max_abs_error,src->max_abs_error,MPFR_RNDN); mpfr_set(dst->l1_error,src->l1_error,MPFR_RNDN); mpfr_set(dst->sd_support,src->sd_support,MPFR_RNDN); mpfr_set(dst->sd_infinite,src->sd_infinite,MPFR_RNDN); mpfr_set(dst->renyi,src->renyi,MPFR_RNDN); mpfr_set(dst->renyi_minus_one,src->renyi_minus_one,MPFR_RNDN); mpfr_set(dst->log2_sd,src->log2_sd,MPFR_RNDN); mpfr_set(dst->log2_renyi_minus_one,src->log2_renyi_minus_one,MPFR_RNDN); mpfr_set(dst->raw_svp_norm,src->raw_svp_norm,MPFR_RNDN); mpfr_set(dst->epsilon,src->epsilon,MPFR_RNDN); mpfr_set(dst->baseline_sd_support,src->baseline_sd_support,MPFR_RNDN); mpfr_set(dst->baseline_sd_infinite,src->baseline_sd_infinite,MPFR_RNDN); mpfr_set(dst->baseline_renyi,src->baseline_renyi,MPFR_RNDN); mpfr_set(dst->candidate_sd_ratio,src->candidate_sd_ratio,MPFR_RNDN); mpfr_set(dst->candidate_renyi_ratio,src->candidate_renyi_ratio,MPFR_RNDN); mpfr_set(dst->acceptance_ratio,src->acceptance_ratio,MPFR_RNDN); mpfr_set(dst->expected_attempts,src->expected_attempts,MPFR_RNDN); mpfr_set(dst->expected_raw_bits,src->expected_raw_bits,MPFR_RNDN);
}
static int better_min_q(const sda_generation_result*c,const sda_generation_result*b,size_t n){ if(!b->q) return 1; if(c->q!=b->q) return c->q<b->q; int cb=draw_bits(c->q), bb=draw_bits(b->q); sda_u128 cg=(((sda_u128)1)<<cb)-c->q, bg=(((sda_u128)1)<<bb)-b->q; if(cg!=bg) return cg<bg; int sd=mpfr_cmp(c->sd_infinite,b->sd_infinite); if(sd) return sd<0; int rd=mpfr_cmp(c->renyi,b->renyi); if(rd) return rd<0; int pe=mpfr_cmp(c->max_abs_error,b->max_abs_error); if(pe) return pe<0; int ep=mpfr_cmp(c->epsilon,b->epsilon); if(ep) return ep<0; for(size_t i=0;i<n;i++) if(c->p[i]!=b->p[i]) return c->p[i]<b->p[i]; return 0; }
static int solve_svp_candidate(const sda_config*cfg,mpfr_t*a,size_t n,mpfr_t eps,sda_generation_result*out){ sda_exact_linf_sda_result svp; sda_exact_linf_sda_init(&svp,n,cfg->mpfr_precision); int rc=sda_exact_linf_sda_solve(a,n,eps,0,&svp); if(rc||!svp.global_svp_certified){ sda_exact_linf_sda_clear(&svp); return rc?rc:-5; }
  out->raw_svp_q=svp.q; out->q=svp.q; out->application_q=svp.q; out->exact_svp_q=svp.q; out->q_bits=sda_bitlength_u128(out->q); out->n=n; out->enumerated_q_count+=svp.q_enumerated; out->raw_svp_vector_available=1; out->exact_linf_svp=svp.exact_linf_svp; out->global_svp_certified=svp.global_svp_certified; out->search_space_exhausted=svp.search_space_exhausted; out->nearest_integer_certified=svp.nearest_integer_certified; out->norm_comparisons_certified=svp.norm_comparisons_certified; out->interval_certified=svp.interval_certified; out->high_precision_verified=svp.high_precision_verified; out->formal_certificate_valid=svp.formal_certificate_valid; out->half_integer_ties=svp.half_integer_ties; out->denominator_from_exact_svp=1; out->fixed_q_optimizer_certified=1; out->denominator_search_complete=0; strcpy(out->solver,"epsilon-svp-generated-min-q"); mpfr_set(out->raw_svp_norm,svp.norm_upper,MPFR_RNDN); mpfr_set(out->epsilon,eps,MPFR_RNDN);
  for(size_t i=0;i<n;i++) out->raw_svp_p[i]=svp.p[i]; sda_u128 sum=0; for(size_t i=0;i<n;i++) sum+=svp.p[i]; out->raw_svp_pmf_valid=(sum==svp.q);
  sda_fixed_q_minmax(a,n,svp.q,out->p,out->max_scaled_error,out->max_abs_error,out->l1_error); sda_build_cumulative(out->p,n,out->c,&out->q); out->pmf_is_fixed_q_normalized=!out->raw_svp_pmf_valid; out->final_q_from_exact_svp=1; finalize_metrics(a,n,out,cfg->renyi_order); out->baseline_dominance_certified=(out->q < (((sda_u128)1)<<cfg->precision_k)) && baseline_ok(out); out->production_eligible=out->baseline_dominance_certified&&out->global_svp_certified; power_metrics(out); mpfr_div(out->candidate_sd_ratio,out->sd_infinite,out->baseline_sd_infinite,MPFR_RNDN); mpfr_div(out->candidate_renyi_ratio,out->renyi,out->baseline_renyi,MPFR_RNDN); sda_exact_linf_sda_clear(&svp); return out->production_eligible?0:-8; }

int sda_generate_for_config(const sda_config*cfg,const char*solver,sda_generation_result*out){
 size_t n=(size_t)(cfg->support_max-cfg->support_min+1); mpfr_t a[32]; for(size_t i=0;i<n;i++) mpfr_init2(a[i],cfg->mpfr_precision); sda_generate_distribution(cfg,a,n,out->tail_mass,out->gaussian_s); int rc=0;
 if(!strcmp(solver,"exact-denominator") || !strcmp(solver,"exact-denominator-search")){
  rc=sda_search_exact_denominator(cfg,a,n,out); strcpy(out->solver,"exact-denominator-search"); out->exact=0; out->exact_linf_svp=0; out->global_svp_certified=0; out->raw_svp_vector_available=0;
 } else if(!strcmp(solver,"exact-linf-svp") || !strcmp(solver,"exact-linf-sda-specialized") || !strcmp(solver,"epsilon-svp-generated") || !strcmp(solver,"epsilon-svp-generated-baseline-dominating-power2-close")){
  if(compute_baseline(cfg,a,n,out)) { rc=-7; }
  else {
    sda_generation_result best; sda_generation_result_init(&best,cfg->mpfr_precision); best.n=n; mpfr_set(best.tail_mass,out->tail_mass,MPFR_RNDN); mpfr_set(best.gaussian_s,out->gaussian_s,MPFR_RNDN); mpfr_set(best.baseline_sd_support,out->baseline_sd_support,MPFR_RNDN); mpfr_set(best.baseline_sd_infinite,out->baseline_sd_infinite,MPFR_RNDN); mpfr_set(best.baseline_renyi,out->baseline_renyi,MPFR_RNDN);
    int trials=cfg->epsilon_initial_trials>1?cfg->epsilon_initial_trials:1; int rounds=cfg->epsilon_refinement_rounds>=0?cfg->epsilon_refinement_rounds:0; int total=trials*(1<<rounds); if(total<1) total=1; if(cfg->epsilon_max_total_instances>0 && total>cfg->epsilon_max_total_instances) total=cfg->epsilon_max_total_instances;
    for(int t=0;t<total;t++){
      double frac=(total==1)?0.5:((double)t/(double)(total-1)); double emin=cfg->epsilon_min>0?cfg->epsilon_min:0.5, emax=cfg->epsilon_max>emin?cfg->epsilon_max:emin; double ev=emin*pow(emax/emin,frac);
      mpfr_t eps; mpfr_init2(eps,cfg->mpfr_precision); mpfr_set_d(eps,ev,MPFR_RNDN);
      sda_generation_result cand; sda_generation_result_init(&cand,cfg->mpfr_precision); cand.n=n; mpfr_set(cand.tail_mass,out->tail_mass,MPFR_RNDN); mpfr_set(cand.gaussian_s,out->gaussian_s,MPFR_RNDN); mpfr_set(cand.baseline_sd_support,out->baseline_sd_support,MPFR_RNDN); mpfr_set(cand.baseline_sd_infinite,out->baseline_sd_infinite,MPFR_RNDN); mpfr_set(cand.baseline_renyi,out->baseline_renyi,MPFR_RNDN);
      int cr=solve_svp_candidate(cfg,a,n,eps,&cand); out->enumerated_q_count += cand.enumerated_q_count;
      if(!cr && cand.production_eligible && better_min_q(&cand,&best,n)) copy_result_core(&best,&cand,n);
      sda_generation_result_clear(&cand); mpfr_clear(eps);
    }
    if(best.q){ copy_result_core(out,&best,n); rc=0; } else { out->baseline_dominance_certified=0; out->production_eligible=0; rc=-8; }
    sda_generation_result_clear(&best);
  }
 } else if(!strcmp(solver,"flint-lll") || !strcmp(solver,"flint-lll-heuristic")){
  if(!sda_lll_available()){rc=-2;} else { sda_lll_smoke_run(); rc=-4; }
 } else rc=-3;
 for(size_t i=0;i<n;i++) mpfr_clear(a[i]); return rc;
}
